open-craft/problem-builder

problem_builder/public/js/mentoring_assessment_view.js
Recreated from https://github.com/open-craft/problem-builder/pull/4
=> Added notifications for locking navigation on supported platforms.

problem_builder/models.py, problem_builder/south_migrations/0001_initial.py, problem_builder/south_migrations/0002_copy_from_mentoring.py
Forward port to master of https://github.com/open-craft/problem-builder/pull/18
=> Hotfix fwd port

problem_builder/public/css/questionnaire.css, problem_builder/public/js/questionnaire.js
This ports two of the CSS fixes found in https://github.com/edx-solutions/xblock-mentoring/pull/110 to Problem Builder. The other CSS fix was already made here. See that PR for full descriptions.
=> Fix two tip CSS issues

.gitignore, problem_builder/answer.py, problem_builder/data_export.py, problem_builder/public/css/data_export.css, problem_builder/public/js/data_export.js, problem_builder/tasks.py, problem_builder/templates/html/data_export.html, problem_builder/tests/integration/test_data_export.py
Adds in the following functionality:
1. Long answer blocks are now exported.
2. User can now filter export results by username, block type, or block ID.
=> Extended export

problem_builder/v1/upgrade.py
This fixes an error that was occurring when upgrading split mongo courses containing Mentoring v1 blocks:
```
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/edx/xblocks/xblock-problem-builder/problem_builder/v1/upgrade.py", line 196, in <module>
upgrade_block(block)
File "/edx/xblocks/xblock-problem-builder/problem_builder/v1/upgrade.py", line 88, in upgrade_block
index = parent_children.index(old_usage_id)
ValueError: BlockUsageLocator(CourseLocator(u'HGSE', u'1x', u'15', None, None), u'mentoring', u'mentoring_first') is not in list
```
The problem was that properties like `block.location`, …
=> Fix issue that can occur when upgrading split mongo courses

circle.yml, setup.py
@bradenmacdonald Decided to make a version  bump for master as well, lest the more progressed branch be a lower version than the release.
=> Bump version.

doc/Dashboard.md
I spent ages trying to figure out how to add a dashboard in studio. This is a pull request to document what I did to get it working.
=> Add instructions for enabling dashboard in studio

circle.yml, setup.py
Bumping the version to 2.6 to mark the improved feature set, and to provide a release version number for edx-platform.
=> Bump version to 2.6.0

circle.yml, setup.py
=> Bumped version to 2.7.0

circle.yml, setup.py
Includes changes from [MCKIN-5248](https://edx-wiki.atlassian.net/browse/MCKIN-5248)
=> Bump version to 2.7.1.

problem_builder/models.py, setup.py
No migration added, per request from @feanil 
OC-3033
=> Remove course_id from answer model.

problem_builder/public/js/mentoring.js, problem_builder/public/js/mentoring_assessment_view.js, problem_builder/public/js/mentoring_standard_view.js, setup.py
Reverts open-craft/problem-builder#177
=> Revert "Adding support for notifying interactions to "mentoring" problem builder"

doc/Native APIs.md, problem_builder/answer.py, problem_builder/tests/unit/test_problem_builder.py, setup.py
This PR adds a `student_view_data` method to the answer recap block.
- Install this revision of problem-builder in your devstack.
- Create a course with a long answer and a recap for it.
- Visit the course blocks API endpoint, e.g.:  `http://YOURLMSURL/api/courses/v1/blocks/?course_id=YOUR/COURSE/ID&username=YOURUSERNAME&depth=all&requested_fields=student_view_data&student_view_data=pb-answer-recap`.
- The JSON response should contain student_view_data for the recap:
```
"i4x://YOUR/COURSE/pb-answer-recap/924467cc658047d2b252df90d041d399": {
"display_name": "Your answer:",
"block_id": "924467cc658047d2b252df90d041d399",
"student_view_url": "http://YOURLMSURL/xblock/i4x://YOUR/COURSE/pb-answer-recap/924467cc658047d2b252df90d041d399",
"student_view_data": {
"type": …
```
=> Add AnswerRecapBlock.student_view_data.

problem_builder/public/css/questionnaire.css, setup.py
- Fixed feedback position in RTL
- updated version
=> RTL feedback for problem Builder

setup.py
https://tasks.opencraft.com/browse/OC-968
=> Bump up version after removing modes.

problem_builder/mentoring.py, problem_builder/step.py, problem_builder/tests/unit/test_problem_builder.py, problem_builder/tests/unit/test_step_builder.py, problem_builder/tests/unit/utils.py, setup.py
Details can be seen on MCKIN-7282 on MCKA Board.
@xitij2000 can you please review this on priority?
=> MCKIN-7282: Embed Ooyala Video Player in Problem Builder and Step Builder

problem_builder/completion.py
Take 2 at fixing the `ModifyingEnforceTypeWarning` that appears in all management command execution attempts in edx-platform master with this XBlock installed.  The earlier attempt was in #176, and further context is in [TE-2585](https://openedx.atlassian.net/browse/TE-2585).  This is one of two remaining warnings that appears for routine management command execution on master, and I'd like to fix both of those in time for Hawthorn if possible.
Currently Hawthorn is slated to use problem-builder 2.7.7; are there any compelling reasons why it shouldn't be updated to use the latest release after this is fixed?
=> Fix student_value field warning

problem_builder/answer.py, problem_builder/choice.py, problem_builder/mcq.py, problem_builder/mentoring.py, problem_builder/mixins.py, problem_builder/mrq.py, problem_builder/tests/unit/test_mixins.py, problem_builder/tests/unit/utils.py, problem_builder/tip.py
Made static urls absolute in Problem builder, mrq and mcq.
=> Make static urls absolute MCKIN-8062-8059

problem_builder/answer.py, problem_builder/choice.py, problem_builder/mcq.py, problem_builder/mentoring.py, problem_builder/mixins.py, problem_builder/mrq.py, problem_builder/tests/unit/test_mixins.py, problem_builder/tip.py
Made urls absolute Mckin-8062-8059
PR for problem-builder-v2 branch.
=> Make static urls absolute MCKIN-8062-8059 (#204)

setup.py
Version bump against this 02887e4ea91c65370f94b709b2a6e5d33f2634ff commit.
=> Updated Version

problem_builder/mcq.py, problem_builder/mentoring.py, problem_builder/mixins.py, problem_builder/mrq.py, problem_builder/step.py, problem_builder/tests/unit/test_problem_builder.py, problem_builder/tests/unit/test_step_builder.py, setup.py
=> MCKIN-8062 expand static urls

problem_builder/answer.py, problem_builder/sub_api.py, requirements.txt, setup.py, test_requirements.txt
MCKIN-8751
In addition to the mentioned block, it looks like some others may not have been configured properly.
Open question: should answer recap be excluded or complete-on-view?
=> MCKIN-8751: Add markers to set completion criteria.

setup.py
=> Bump version to 2.11.1

setup.py
version bump for c45c09b (translations update)
=> version bump to 2.11.2 (translations update)

problem_builder/mrq.py, setup.py
Code modified to fetch Tips only once for every MRQ problem inside calculate_results method.
@bradenmacdonald Can you take a look at this PR. 
Ticket link: https://openedx.atlassian.net/browse/YONK-1219
=> YONK-1219 - Code optimization for more performance

problem_builder/mrq.py, setup.py
Code modified to fetch Tips only once for every MRQ problem inside calculate_results and student_view_data method.
@xitij2000 Can you take a look at this PR.
Ticket link: https://openedx.atlassian.net/browse/YONK-1219
=> YONK-1219 - Code optimization for more performance - rebase on master

problem_builder/answer.py, problem_builder/sub_api.py, problem_builder/tasks.py, requirements.txt, setup.py, test_requirements.txt
This PR moves changes from [problem-builder-v2](https://github.com/open-craft/problem-builder/tree/problem-builder-v2) to problem-builder-v3.
Check that problem builder blocks can be created and submitted.
=> [MCKIN-8350] Incorporate recent changes in problem-builder v2 into problem-builder v3

.coveragerc, README.md, circle.yml, pylintrc, test_requirements.txt, tox.ini
Parallelize test to run quality and unit/integration tests in different containers.
=> BB-1128 Update circle.yml

setup.py
=> Bump version to `v3.3.13`

problem_builder/public/js/mentoring_with_steps.js, setup.py
When all the attempts are utilized, and the user reviews the responses, The video keeps on playing when he clicks the next question.
=> MCKIN-12576 Pause videos on reviewNextStep

setup.py
Reverts open-craft/problem-builder#312
=> Revert "Add translations to the package data"

setup.py
This pr https://github.com/open-craft/problem-builder/pull/312 was already approved but it was reverted since it needed a bumpversion, This includes both changes.
@aayushagra
=> Add translations to the package data
