- .travis.yml
- problem_builder/questionnaire.py
- problem_builder/tests/integration/xml/assessment_1.xml
- problem_builder/tests/integration/xml/assessment_2.xml
- problem_builder/tests/integration/xml/mcq_1.xml
- problem_builder/tests/integration/xml/mcq_with_comments_1.xml
- problem_builder/tests/integration/xml/mcq_with_fixed_height_tips.xml
- problem_builder/tests/integration/xml/mcq_with_html_choices.xml
- problem_builder/tests/integration/xml/mrq_with_html_choices.xml
- problem_builder/tests/integration/xml/theme_1.xml
- problem_builder/tip.py
- problem_builder/v1/tests/test_upgrade.py
- problem_builder/v1/tests/xml/v1_upgrade_a_new.xml
- problem_builder/v1/tests/xml/v1_upgrade_b_new.xml
- problem_builder/v1/xml_changes.py
- test_requirements.txt
Same as #5, just merging to `develop` directly.
> Remove custom deserialization code

- problem_builder/public/css/questionnaire.css
- problem_builder/public/themes/apros.css
- problem_builder/public/themes/lms.css
- problem_builder/questionnaire.py
- problem_builder/tests/integration/test_dashboard.py
Apros CSS has the rule `*, *:before, *:after { box-sizing: border-box; }`, which (not surprisingly) messes up the layout of our tip popups.
**Before screenshot**:
**After screenshot**:
* Use a birch rebase branch of the solutions fork of edx-platform. The only one that's currently working for me is [braden/birch-rebase-testing](https://github.com/edx-solutions/edx-platform/commits/braden/birch-rebase-testing)
* Add the following to `~/lms.env.json`:
```json
"XBLOCK_SETTINGS": {
"mentoring": {
"theme": {
"package": "problem_builder",
"locations": ["public/themes/apros.css"]
}
}
}
```
* Open Apros and look at an MCQ/MRQ with tips.
> Fix invalid appearance in Apros due to their box-sizing global

- problem_builder/mcq.py
- problem_builder/mentoring.py
- problem_builder/public/css/mentoring.css
- problem_builder/public/js/mentoring_assessment_view.js
- problem_builder/questionnaire.py
**Description**: The `edx-release` branch contains only the code that has been reviewed by both OpenCraft and edX for release on edX.org. In testing that release branch, we found a few minor issues which this PR addresses.
Fixes:
* Bug: MCQ/MRQ question titles were not visible in the LMS, even when "Show Title" was true, if another MCQ/MRQ that came earlier in the same subsection had show_title set false.  
Fixed with 45072bbc661d9306fa751295e276827ab5fef3b7
* Usability improvement: In Studio, an MCQ's question text could not be set until at least one choice was created. In addition, a validation warning was shown immediately when adding an MCQ.  
Fixed with 3d4bf295bd760526a97735102fb448ccb28889a9
* Bug: If a problem builder in assessment mode had max_attempts=2, then a student completes …
> Hotfix: Four minor issues to address before release

- problem_builder/mcq.py
- problem_builder/mentoring.py
- problem_builder/public/css/mentoring.css
- problem_builder/public/js/mentoring_assessment_view.js
- problem_builder/questionnaire.py
These five fixes were made on the release branch. This PR brings them to our main master branch.
The code was reviewed in #9.
> Five fixes from edx-release

- problem_builder/public/js/mentoring.js
- problem_builder/public/js/mentoring_assessment_view.js
- problem_builder/public/js/mentoring_standard_view.js
I found an issue while testing birch rebase: If a Problem Builder contains a Long Answer field with a "name" that is numeric (e.g. "1234"), then the checkmark does not appear after you submit your answer. (Everything works fine though, just the checkmark is missing).
> Fix: Checkmark not shown if answer name is numeric

- problem_builder/answer.py
- problem_builder/mentoring.py
- problem_builder/public/js/mentoring_standard_view.js
- problem_builder/questionnaire.py
- problem_builder/step.py
- problem_builder/table.py
- problem_builder/templates/html/answer_editable.html
- problem_builder/templates/html/mcqblock.html
- problem_builder/templates/html/mentoring.html
- problem_builder/templates/html/mrqblock.html
- problem_builder/templates/html/ratingblock.html
- problem_builder/tests/integration/test_multiple.py
- problem_builder/tests/integration/test_questionnaire.py
- problem_builder/tests/integration/test_titles.py
- problem_builder/tests/integration/xml/mcq_with_html_choices.xml
- problem_builder/tests/integration/xml/mrq_with_html_choices.xml
- problem_builder/tests/integration/xml/multiple_problem_builders.xml
- problem_builder/v1/tests/test_upgrade.py
- problem_builder/v1/tests/xml/v1_upgrade_b_new.xml
- problem_builder/v1/tests/xml/v1_upgrade_b_old.xml
- problem_builder/v1/tests/xml/v1_upgrade_c_new.xml
- problem_builder/v1/tests/xml/v1_upgrade_c_old.xml
- problem_builder/v1/tests/xml/v1_upgrade_d_new.xml
- problem_builder/v1/tests/xml/v1_upgrade_d_old.xml
- problem_builder/v1/upgrade.py
- problem_builder/v1/xml_changes.py
This fixes some bugs in the upgrade script that upgrades a course from mentoring v1 to problem builder.
There is one fix per commit. The issues fixed are:
* Minor unicode error
* If `<title></title>` was present, it would cause an error because etree empty tags have `.text` value set to `None` rather than `""`
* The third is more interesting: when a unit (vertical) contained two mentoring blocks, the first one would disappear after the upgrade. The reason was aggressive caching of the "children" property by the platform. I bypassed some caching and it fixed the bug.
* Support for upgrading assessments that consisted of alternating `<html>` and `<mcq>` (or similar) blocks that were intended to be displayed at the same time.
* The upgrade script will now discard empty tips like `<tip …
> Fix upgrade bugs

- problem_builder/dashboard.py
- problem_builder/public/css/dashboard.css
- problem_builder/templates/html/dashboard.html
- problem_builder/tests/integration/test_dashboard.py
- problem_builder/tests/integration/xml/dashboard.xml
**JIRA Ticket:** https://openedx.atlassian.net/browse/OSPR-543
**Details:** See JIRA ticket
**Sandbox:** [LMS](http://sandbox4.opencraft.com/courses/course-v1:edX+PB101+now/courseware/ee978680a3bc409a93e1e5d2efac7787/1654a7e6c6244bb18d6fd729b9f26557/), [CMS](http://sandbox4.opencraft.com:18010/container/block-v1:edX+PB101+now+type@vertical+block@977dea6433d044ddaac7389138175751?action=new)
**Merge deadline:** Friday 24th (in time for upcoming release)
1. Set up a couple of mentoring XBlocks
2, Set up Dashboard block to draw data from those blocks
3. Set custom value for "Label for average value"
4. Set "Display numeric values" to False
5. Set some "Questions to be hidden" (see help string). Note that only questions are counted toward question index, e.g. if …
> Presentation updates

- problem_builder/models.py
- problem_builder/south_migrations/0001_initial.py
- problem_builder/south_migrations/0002_copy_from_mentoring.py
Hotfix for OC-639:
**Bug details**:
The old mentoring XBlock uses South migrations to create a table called `mentoring_answers`. The new Problem Builder XBlock uses syncdb to create a table also called `mentoring_answers`.
Unfortunately, if a new edX instance is spun up and mentoring v1 and Problem Builder are both being installed at the same time (as they are if `requirements/edx/edx-private.txt` is used), there will be a database error since the South migration will abort when it finds that the table already exists: https://gist.github.com/maxrothman/3868d5e7ad87533a287c
Because syncdb does nothing if the table already exists, an edX instance could only have both blocks installed as long as mentoring was installed and setup in the DB first.
**Fix details**:
My proposed fix is just to …
> Hotfix for OC-639: Database conflict between mentoring and problem_builder

- problem_builder/dashboard.py
- problem_builder/templates/html/dashboard.html
- problem_builder/tests/integration/test_dashboard.py
**JIRA Ticket:** https://openedx.atlassian.net/browse/OSPR-543
**Details:** See JIRA ticket
**Sandbox:** [LMS](http://sandbox4.opencraft.com/courses/course-v1:edX+PB101+now/courseware/ee978680a3bc409a93e1e5d2efac7787/1654a7e6c6244bb18d6fd729b9f26557/), [CMS](http://sandbox4.opencraft.com:18010/container/block-v1:edX+PB101+now+type@vertical+block@977dea6433d044ddaac7389138175751?action=new)
**Merge deadline:** Preferably Friday 24th (in time for upcoming release).
1. Set up a couple of mentoring XBlocks
2, Set up Dashboard block to draw data from those blocks
3. Set custom values for "Label for average value" for some (or all) mentoring blocks
4. Publish
5. Go to LMS, provide answers for mentoring blocks
6. Navigate to dashboard block
Observe the following:
* …
> Allowed overriding average labels per mentoring

- .travis.yml
- problem_builder/mentoring.py
- problem_builder/message.py
- problem_builder/public/css/mentoring_edit.css
- problem_builder/public/js/answer.js
- problem_builder/public/js/mentoring_edit.js
- problem_builder/public/js/mentoring_standard_view.js
- problem_builder/tests/integration/base_test.py
- problem_builder/tests/integration/test_assessment.py
- problem_builder/tests/integration/test_dashboard.py
- problem_builder/tests/integration/test_messages.py
- problem_builder/tests/integration/test_progression.py
- problem_builder/tests/integration/xml_templates/dashboard.xml
- problem_builder/tests/integration/xml_templates/messages.xml
This fixes OC-667 (upstream bug is a comment in SOL-423): The "Message (max # attempts)" component was not working.
**Explanation**:  
`get_message()` was called before `num_attempts` was incremented, so the `max_attempts_reached` message would never be used, since `num_attempts` was always less than `max_attempts` at that point.
**Notes**:  
I wanted to just do a simple fix, which involves moving the `get_message()` method to after where `num_attempts` is updated, but the implications of that move were not at all clear due to the complexity of the "submit" handler, and uncertainty about when the various messages are even supposed to be display. So I added a bunch of new tests and documentation to clarify the expected behavior of each type of message (I hope I got it right), and I also …
> Fix max attempts message

- problem_builder/public/css/mentoring.css
- problem_builder/public/js/mentoring_assessment_view.js
- problem_builder/public/js/mentoring_standard_view.js
The link is only used during extended feedback in assessment mode.  It's hidden
on page load by JS in all cases, and only shown if the student goes back to a
question after using up all attempts, so we can just as well hide it in CSS.
This fixes MCKIN-3099.
@bradenmacdonald I can't reproduce the issue on my local Apros installation, neither with Firefox nor with Chrome.  I can reproduce it using the link and credentials in MCKIN-3099, though, so it's probably dependent on the timing of AJAX responses, or something along these lines.  Could you please try whether you are able to reproduce the issue, and whether this patch fixes it?  I'm rather confident it does.
The issue occurs when moving forward (or back) to a unit with a mentoring question in standard mode using the blue Apros …
> Hide "Review final grade" link by default.

- problem_builder/public/css/mentoring.css
- problem_builder/templates/html/mentoring_grade.html
Style tweaks to match more closely the comp:
* Adds horizontal margin on the side of the grades results
* Moves the bottom line separator to the same block (instead of only showing it when the assessment feedback block is shown)
* Reduce the boldness of the text on assessments results
> Assessment style tweaks

- .travis.yml
- problem_builder/dashboard.py
- problem_builder/mentoring.py
- problem_builder/public/css/dashboard.css
- problem_builder/public/js/mentoring.js
- problem_builder/public/js/mentoring_standard_view.js
- problem_builder/templates/html/dashboard.html
- problem_builder/templates/html/dashboard_report.html
- problem_builder/templates/html/mentoring.html
- problem_builder/tests/integration/test_dashboard.py
- run_tests.py
**Fixes and improvements:**
* Give all the tables of the dashboard the same width (should be ~700px to give enough place to display long titles), and center the tables
* Increase the width of the color codes in the table, to make them squarred instead of rectangular
* Make the label for the "Average" row in the tables semi-bold (font-weight: 600)
* Change aria-labels to off-screen text, as per Mark Sadeki's accessibility review: https://github.com/open-craft/problem-builder/pull/16#discussion_r29346587
* In the export HTML:
** Use left alignment for text within the tables, which is currently shown centered<
** Apply the changes done to the table in the LMS: center the tables, use the same width for all tables (~700px - do not make it stretch to all available space, as widows can be big …
> Presentation updates, part 2

- problem_builder/dashboard.py
- problem_builder/templates/html/dashboard.html
- problem_builder/tests/integration/test_dashboard.py
This patch allows course authors to add custom texts at the top and bottom of the downloadable self-assessment summary reports.
This has been reviewed in #35 (that PR targeted the wrong branch).
Partner information: hosted on edx.org (Harvard)
Merge deadline: Thursday, 22 May, for inclusion in this week's release
Sandbox: http://sandbox4.opencraft.com:18010/course/course-v1:OpenCraftX+0815+2015 (log in with the standard staff user)
For testing, go to the "Summary report" unit of the linked course and click SETTINGS on the single component in that unit.  The new fields are at the very bottom of the settings dialogue.
> Allow to include an HTML header and footer in reports.

- problem_builder/mentoring.py
- problem_builder/tests/integration/base_test.py
- problem_builder/tests/integration/test_author_changes.py
- problem_builder/tests/integration/xml_templates/author_changes.xml
This is a follow up to #25 - it turns out I missed another failure mode (if you delete the last step, while the student is on that step).
> Test + fix an additional failure case

- problem_builder/message.py
- problem_builder/v1/tests/xml/v1_upgrade_a_new.xml
- problem_builder/v1/tests/xml/v1_upgrade_a_old.xml
This PR addresses OC-694. The issue was caused by the XML parser expecting the "type" attribute to always be present, when in fact it is optional and has a default value of "completed".
I fixed the custom xml parser so it doesn't require that attribute, and I updated the relevant test to check for this.
> Fix upgrade error when <message> has no 'type' specified explicitly

- problem_builder/public/themes/apros.css
- problem_builder/tests/integration/base_test.py
- problem_builder/tests/integration/test_mentoring.py
- requirements.txt
- test_requirements.txt
When the Apros theme is active, this makes the main header (an `h2`) match the color of Apros `<h2 class="main">` headers. It also makes the subheaders use all-caps, as Apros does.
Screenshot:
> Minor tweaks to better match the Apros theme

- problem_builder/__init__.py
- problem_builder/data_export.py
- problem_builder/public/css/data_export.css
- problem_builder/public/js/data_export.js
- problem_builder/tasks.py
- problem_builder/templates/html/data_export.html
- problem_builder/tests/integration/test_data_export.py
- setup.py
This new **Data Export Block** provides an instructor interface for generating CSV exports of student answers to problems in the course. The actual export of answers to CSV is done by a new celery task, which integrates with the existing `ReportStore` API functionality to save the CSV file to S3.
Screenshot:
Testing:
To test with celery on devstack, configure rabbitmq then run `paver celery --settings=devstack`. Edit `lms/envs/devstack.py` to set `CELERY_ALWAYS_EAGER = False`.
> Data Export block prototype

- problem_builder/data_export.py
- problem_builder/public/js/data_export.js
- problem_builder/tasks.py
@mtyaka @itsjeyd 
This PR contains two commits-- one of which is for the issue of missing children causing a crash, and one may resolve the issue where the download button was hidden.
A few notes:
1. I don't have access to the Harvard instance, and I can't reproduce this locally, so this fix is my best guess. I might have an easier time of it if I can see it in person. @mtyaka , would you be able to show me where this is and get me set up with it?
2. The primary fix for the download button is fixing a conditional that would always be true (objects only ever equal themselves in Javascript. Deep equality is not checked). I believe that this assumption might cause a race condition whereby the updateStatus information might be updated twice rapidly with two different sets of information.
3. A …
> Export bugfixes

- problem_builder/instructor_tool.py
- problem_builder/public/css/instructor_tool.css
- problem_builder/public/js/instructor_tool.js
- problem_builder/tasks.py
- problem_builder/templates/html/instructor_tool.html
- problem_builder/tests/integration/test_instructor_tool.py
This PR improves UX for the "Instructor Tool" XBlock by introducing a dropdown menu for constraining the set of exported answers to a specific block in the course outline:
It also enables client-server communication for pagination functionality introduced in #45. This means that instead of transferring all results to the client when the export process finishes and paginating them there, at most `PAGE_SIZE` items (currently: 15) are transferred at a time. This is not a user-facing change (except for the fact that navigating between result pages takes a little bit longer now that the client has to communicate with the server to obtain more data).
From Studio:
1. Add `pb-instructor-tool` to advanced modules.
2. Add one or more MCQs/rating questions/long answer blocks to a unit.
3. Add an …
> Instructor Tool: Drop-down for "Root block ID" section, pagination improvements (OC-783)

- problem_builder/public/css/mentoring-table.css
- problem_builder/public/js/review_blocks.js
- problem_builder/table.py
- problem_builder/templates/html/mentoring-table-container.html
- problem_builder/templates/html/mentoring-table-shared-list.html
@antoviaque Hopefully these should address your notes.
Note, instead of making an extra download button, I placed the link where you suggested. Adding a download button would have prompted a lot more work in terms of alignment of the pop-ups and notifications, and I felt that it would be better to just place it down below.
> Visual improvements to Table block.

- problem_builder/public/js/mentoring.js
This fixes a JS error that would occur when a PB block contains an HTML child followed by an answer block: `TypeError: Cannot read property 'toString' of undefined`
The reason for the error is that HTML blocks don't have a `name` property. This fix is simple. Unfortunately I couldn't figure out how to add a regression test for this, since the workbench runtime doesn't appear to have this bug - only the edx-platform runtime.
**Sandbox** URL that previously had the issue: http://sandbox2.opencraft.com/courses/course-v1:HGSE+1x+2015/courseware/Week_1_Welcome_and_orientation/Change_Diary_Using_the_Change_Diary/
> Fix JS bug when HTML block is followed by an answer block

- problem_builder/v1/tests/test_upgrade.py
- problem_builder/v1/upgrade.py
- problem_builder/v1/xml_changes.py
JIRA: OC-805
It was discovered that when migrating from [the old gsehub version of xblock-mentoring](https://github.com/edx/edx-platform/blob/4b4ce5f1226a49840/requirements/edx/edx-private.txt#L4), "Question" titles get added to every question even though they were never an option in that version. When migrating from the edx-solutions version, "Question" titles are added because they are the default in that version.
I have added a new option to the migration script that allows the user to toggle "v0" upgrade, which will set "show_title" to False by default on each answer/mcq/etc. We cannot change the behavior in general, because titles are shown by default in the most recent versions of xblock-mentoring v1.
Example usage:
```
SERVICE_VARIANT=cms \ …
```
> Allow toggling show_title behaviour during upgrade (OC-805)

- problem_builder/answer.py
- problem_builder/mentoring.py
- problem_builder/public/js/answer.js
- problem_builder/public/js/answer_recap.js
- problem_builder/templates/html/answer_editable.html
- problem_builder/templates/html/answer_read_only.html
- problem_builder/tests/unit/test_mentoring.py
JIRA: OC-839
This fixes:
Bug 1
-------
The LMS sequential ("subsection") displays tooltips in its accordion unit selector according to a strange criterion: If there are zero or one child blocks in the "Unit" (vertical block) and there is no title set on that child, then the Unit's title is used. Otherwise, the recursively combined titles of all child blocks are shown.
This caused an apparent regression when upgrading from mentoring to problem builder, in a course with no titles set on any of the mentoring/pb blocks: Since Problem Builder now declares a title ("Mentoring Questions") by default, that title was being used instead of the unit's title.
To fix this, I have changed the `get_content_titles` method to only return a title to the LMS if a title is set explicitly.
Before:
After:
Bug …
> Fix two bugs (OC-839)

- problem_builder/public/themes/lms.css
JIRA: OC-839
On the Harvard GSE instance, Problem Builder's LMS theme was not rendering correctly. The issue turned out to be that some of the theme's CSS rules had the same specificity as the "unthemed" rules, so that which one would be used was ambiguous.
Screenshot showing [desired interpretation](https://cloud.githubusercontent.com/assets/945577/8925664/6188fa46-34be-11e5-91eb-b3ac7bd19f0f.png) and [valid but wrong interpretation](https://cloud.githubusercontent.com/assets/945577/8925665/6bf3de38-34be-11e5-998e-e3642589572b.png).
Fix was to add an extra CSS selector to each of the rules in question.
> Add an extra selector to fix CSS rule ambiguity

- problem_builder/mentoring.py
- problem_builder/tests/integration/test_progression.py
- problem_builder/tests/unit/test_mentoring.py
**Description**: We ran into [a weird issue](PLAT-772) in a live course, where `get_block` returned `None` in the following code:
```python
for child_id in self.children:
child = self.runtime.get_block(child_id)
```
Since we didn't expect `child` ever to be `None` with that API, this resulted in `AttributeError: 'NoneType' object has no attribute 'render'`, causing the whole subsection of the LMS to be replaced with a 500 error.
Although `get_block` *shouldn't* return `None` if everything is working, it is an expected return value when an error occurs, so we should be able to handle it gracefully.
I added an error message to the rendered HTML so that there will at least be some indication that content is missing - otherwise this could result in content silently disappearing for students …
> Don't cause a 500 error in the LMS if get_block unexpectedly returns None

- problem_builder/instructor_tool.py
- problem_builder/tests/integration/test_instructor_tool.py
- problem_builder/tests/unit/test_instructor_tool.py
This PR aims to extend unit test coverage for problem-builder by introducing unit tests for the Instructor Tool block.
It follows up on #47.
> Add unit tests for instructor tool

- problem_builder/instructor_tool.py
- problem_builder/public/js/instructor_tool.js
- problem_builder/tasks.py
- problem_builder/templates/html/instructor_tool.html
This PR extends existing functionality of the instructor tool by allowing users to enter multiple usernames to search for answers from multiple users simultaneously.
The input field for entering usernames expects usernames to be separated by commas, but is not sensitive to whitespace (meaning that commas can be surrounded by arbitrary amounts of whitespace).
From Studio:
1. Add `pb-instructor-tool` to advanced modules.
2. Add one or more MCQs/rating questions/long answer blocks to a unit.
3. Add an instructor tool block to the same or another unit.
From the LMS:
1. Sign in as `staff` and provide answers to some of the MCQ/rating questions/long answers blocks.
2. Repeat previous step for `honor`, `audit`, etc.
3. Sign in as `staff` and switch to instructor tool. Enter usernames of one or …
> Instructor Tool: Support searching for answers from multiple users

- problem_builder/mentoring.py
`MentoringBlock.get_message` currently returns an unintuitive result which doesn't contain the message itself but a template of it. This PR modifies the method to return a message instead.
> Simplify get_message: Return message instead of template

- problem_builder/table.py
- problem_builder/tests/integration/test_table.py
- problem_builder/tests/integration/xml/table_3.xml
In the LMS, links of the form `/jump_to_id/<unit identifier>` are currently not translated/expanded correctly when they are part of a table column header. For example,
/jump_to_id/mentoring_reflecting_on_feedback
correctly expands to
https://openedx.gse.harvard.edu/courses/course-v1:HGSE+IOCEX+2015_T1/jump_to_id/mentoring_reflecting_on_feedback
when added to an HTML block. But when added to the column header of an Answer Recap table the expanded URL ends up missing information about the parent course (leading to an invalid link):
https://openedx.gse.harvard.edu/jump_to_id/mentoring_reflecting_on_feedback
This PR adds code that makes sure links to course units that are part of table column headers are expanded correctly inside the LMS.
**Testing**
1. Download a copy of the …
> Fix: Translate links in table column headers

- problem_builder/mentoring.py
- problem_builder/message.py
- problem_builder/public/css/problem-builder.css
- problem_builder/public/css/questionnaire-edit.css
- problem_builder/public/js/mentoring_assessment_view.js
- problem_builder/public/js/questionnaire_edit.js
- problem_builder/public/themes/apros.css
- problem_builder/questionnaire.py
- problem_builder/step.py
- problem_builder/templates/html/mentoring.html
- problem_builder/templates/html/mentoring_assessment_templates.html
- problem_builder/templates/html/mentoring_review_questions.html
- problem_builder/templates/html/questionnaire_add_buttons.html
- problem_builder/tests/integration/test_assessment.py
- problem_builder/tests/integration/xml_templates/assessment.xml
This new feature allows content authors to set an optional "review message" on each MCQ/MRQ/Rating question.
The review messages are shown in assessment mode when the student is reviewing their grade before being allowed to try again. The review screen now includes a list of topics to review, based on which questions the student got wrong.
Screenshot:
If the student got all the questions right or has no attempts remaining, the new review section is not shown.
Here's how it looks to course authors in Studio:
> Assessment targeted review

- problem_builder/__init__.py
- problem_builder/answer.py
- problem_builder/choice.py
- problem_builder/mcq.py
- problem_builder/mentoring.py
- problem_builder/message.py
- problem_builder/mixins.py
- problem_builder/mrq.py
- problem_builder/public/css/problem-builder-edit.css
- problem_builder/public/js/mentoring_with_steps_edit.js
- problem_builder/public/js/step_edit.js
- problem_builder/questionnaire.py
- problem_builder/step.py
- problem_builder/table.py
- problem_builder/templates/html/step.html
- problem_builder/tests/unit/test_step.py
- problem_builder/tip.py
- requirements.txt
- setup.py
This PR introduces two new blocks and enables support for viewing and editing them in Studio. One of the blocks is a new version of `MentoringBlock` that supports explicit steps, the other one is a block that represents a step:
-  The new mentoring block only allows step blocks (any number) and mentoring-wide messages as direct children.
-   The step block hosts all blocks that can not be added to new mentoring block (MCQ, MRQ, Long Answer, etc.)
**Acceptance criteria**
Studio integration:
-   [X] Make it possible to add new mentoring block to unit
-   [X] Make it possible to **add** step blocks
-   [X] Make it possible to **edit** step blocks
-   [X] Make it possible to **remove** step blocks
-   [X] Make it possible to **add step contents**
-   [X] Previews at mentoring and step levels …
> New version of mentoring block that supports explicit steps

- AUTHORS
- problem_builder/mentoring.py
- problem_builder/public/js/mentoring_with_steps.js
- problem_builder/public/js/step.js
- problem_builder/step.py
- problem_builder/templates/html/mentoring_with_steps.html
This PR adds step navigation and submission functionality to the new blocks introduced in #62.
* New mentoring block now displays one step at a time.
* New step block allows to submit step results. Info about last step submitted is saved at mentoring level so users are taken to the correct step when resuming their work (or reloading the page).
* New mentoring block allows to navigate to next step after submitting step results.
* After submitting the last step, new mentoring block displays a "Try again" button that allows to reset the block and start from scratch. (This functionality will be moved to the review step as part of OC-913.)
**Screenshots**
New mentoring block displaying a single step (with multiple questions):
After submitting the current step (all answers correct):
After …
> Step navigation and submission for new mentoring block

- problem_builder/mentoring.py
- problem_builder/tests/unit/test_mentoring.py
@bradenmacdonald @e-kolpakov @antoviaque 
To test this:
1. Create an MCQ with a message sub-block that has a /jump_to_id/<id_hash> url link in it.
2. Add in a message feedback block that also has one.
3. Set the mode to assessment.
4. Fail to answer the MCQ correctly, see the results page, check the links to see if they work.
> Make sure messages get jump_to_id URLs rewritten.

- problem_builder/mentoring.py
- problem_builder/tests/unit/test_mentoring.py
This PR fixes the following regression:
If the last question belonging to a mentoring block is an MCQ/MRQ and has no "Assessment Review" message component, it can't be submitted. The error happens only when trying to submit a wrong answer.
**Testing**
1. Add Problem Builder block to unit.
2. Temporarily enable mode switching by adding `mode` to `editable_fields` (mentoring.py, line 321):
```python
editable_fields = (
'display_name', 'followed_by', 'max_attempts', 'enforce_dependency',
'display_submit', 'feedback_label', 'weight', 'extended_feedback', 'mode'
)
```
This is necessary because mode switching was disabled in #66 (as a first step towards deprecating assessment functionality of Problem Builder), and the bug only affects assessment mode.
3. Set mode to "assessment".
4. Add an MCQ, …
> Problem Builder: Fix submission of incorrect questions without review tips

- problem_builder/public/js/mentoring_with_steps.js
- problem_builder/public/js/mentoring_with_steps_edit.js
- problem_builder/public/js/review_step_edit.js
This PR fixes the following issues:
1. When removing a Review Step child from a Step Builder block, the button for adding it stays greyed out, making it impossible to remove and then re-add a Review Step block (without reloading the page). The same issue also affects buttons for adding different types of message children to Review Step block.
2. In supporting runtimes (i.e., Apros), arrow buttons for navigating between units should be disabled while completing Step Builder blocks; they should become available again when user reaches review step.
**Testing**
For the first issue:
1. Add a Step Builder block to a unit.
2. Add a Review Step block to Step Builder. (Observe that the corresponding button is greyed out.)
3. Remove the Review Step block. Observe that the corresponding button is …
> Step Builder: Allow re-adding children after removing them and (un)lock unit navigation when appropriate

- problem_builder/__init__.py
- problem_builder/tests/integration/base_test.py
- problem_builder/tests/integration/test_mcq.py
- problem_builder/tests/integration/test_mentoring.py
- problem_builder/tests/unit/test_mentoring.py
- problem_builder/tests/unit/test_migration.py
- problem_builder/v1/tests/test_upgrade.py
- setup.py
- test_requirements.txt
OC-1003
This fixes [TNL-3563](https://openedx.atlassian.net/browse/TNL-3563).
The `pb-dashboard` block was not loading due to a bizarre combination of factors, brought into play by the recent [django-rest-framework upgrade](https://github.com/edx/edx-platform/pull/9831).
**Details**:
The error was being reported as:
```
File "/edx/xblocks/xblock-problem-builder/problem_builder/dashboard.py", line 415, in student_view
value = sub_api.get_submissions(mcq_submission_key, limit=1)[0]["answer"]
AttributeError: 'NoneType' object has no attribute 'get_submissions'
```
To get the true error, I had to remove a `try: ... except ImportError` wrapper, and then we can see the real cause:
```
Traceback (most recent call last):
File "manage.py", line 116, in <module> …
```
> Fix: Don't import all the problem builder blocks when the django app is loaded

- problem_builder/public/js/mentoring_with_steps.js
- problem_builder/public/js/step.js
- problem_builder/step.py
- problem_builder/templates/html/step.html
- problem_builder/tests/integration/test_step_builder.py
- problem_builder/tests/integration/xml_templates/step_builder_next.xml
@itsjeyd Ready for your review.
You should be able to test this by:
1. Adding 'step-builder' to the advanced modules.
2. Creating a step-builder block.
3. Adding a Mentoring step block to the step-builder block
4. Adding a question and review to the Mentoring step block
5. Editing the mentoring step block to change the next button label text.
6. Publishing
7. Trying the step in the LMS to see if the next button has your customized text
Heads up @e-kolpakov , this should be coming down the pipe soon, and needs to be included in the release.
> Make 'next' button text customizable in Mentoring Steps.

- problem_builder/answer.py
- problem_builder/public/js/mentoring_with_steps.js
- problem_builder/public/js/step.js
- problem_builder/questionnaire.py
- problem_builder/step.py
- problem_builder/templates/html/step.html
- problem_builder/tests/integration/test_step_builder.py
- problem_builder/tests/integration/xml_templates/step_builder.xml
- problem_builder/tests/integration/xml_templates/step_builder_html_last.xml
To test:
1. Add 'step-builder' to advanced modules.
2. Create a step builder block.
3. Create a few steps within the step builder block.
4. Fill some with nothing but fluff, others with questions
5. Make sure you can move through the fluff steps without disrupting functionality of the questions
6. Make sure the button semantics make sense-- next or review where appropriate
@e-kolpakov
> Enable seamless use of steps that have no questions.

- .gitignore
- problem_builder/step.py
- problem_builder/tests/unit/test_step.py
- requirements.txt
- run_tests.py
@mtyaka 
Testing instructions:
1. Create a course, add 'step-builder' to the advanced modules.
2. Add step builder block, add Mentoring Step to that block.
3. You should see Video block is available for adding. Add one to see if it works.
4. Stop CMS, install https://github.com/Stanford-Online/xblock-image-modal
5. Go back to Mentoring Step block in the CMS
6. See Image Modal in the available blocks list for adding. Add one to see if it works.
> Allow Videos and images to be added to Mentoring Step Block.

- .travis.yml
- problem_builder/answer.py
- problem_builder/mixins.py
- problem_builder/public/css/problem-builder-edit.css
- problem_builder/public/css/problem-builder.css
- problem_builder/public/js/mentoring_standard_view.js
- problem_builder/public/js/slider.js
- problem_builder/questionnaire.py
- problem_builder/slider.py
- problem_builder/step.py
- problem_builder/templates/html/mentoring_add_buttons.html
- problem_builder/templates/html/slider.html
- problem_builder/templates/html/slider_edit_footer.html
- problem_builder/tests/integration/test_slider.py
- problem_builder/tests/integration/xml_templates/slider_problem.xml
- problem_builder/tests/integration/xml_templates/slider_step.xml
- problem_builder/tests/unit/test_step.py
- setup.py
This adds a new "Scale" block (actually I called it "Ranged Value Slider" but can change if needed):
**Screenshot**:
> Step Builder: New question type: "Scale" (OC-1009)

- .travis.yml
- problem_builder/mentoring.py
OC-1033
**Fix Description**
Without this fix, Problem Builder blocks do not appear on a student's "Progress" page until the student has submitted a grade. The reason was that Problem Builder did not implement the `max_score()` method.
**Potential Further Improvement**
Problem Builder blocks currently return scores as floating point values between `0` and `1`. It would be better to return integer numerator/denominator pairs (simpler for students, more reliable, more consistent with CAPA modules). However, changing that in the middle of any live course could cause some students' scores to be weighted differently than others. (e.g. Student A could have a score of '0.5/1' while student B could submit the same answer post-upgrade and get a score of '1/2' - which is theoretically the same but …
> Fix: Problem Builder does not show on Progress page until student submits an answer (OC-1033)

- problem_builder/plot.py
- problem_builder/public/css/overlay.css
- problem_builder/public/css/plot-preview.css
- problem_builder/public/css/plot.css
- problem_builder/public/css/problem-builder-edit.css
- problem_builder/public/js/plot.js
- problem_builder/public/js/plot_edit.js
- problem_builder/templates/html/overlay.html
- problem_builder/templates/html/plot.html
- problem_builder/templates/html/plot_preview.html
- problem_builder/tests/integration/test_step_builder.py
- problem_builder/tests/integration/xml_templates/step_builder_plot_overlays.xml
- setup.py
This PR follows up on #77 and adds functionality for defining custom overlays for plot blocks.
**Testing**
1. Add Step Builder to a unit.
2. Add two Mentoring Step blocks and a Review Step block to Step Builder.
3. Add two Rating questions to the first Mentoring Step block.
4. Add a Plot block to the second Mentoring Step block.
5. For each of the Rating questions, grab the corresponding "Question ID" from the EDIT dialog in Studio (last field, underneath "Label for high ratings").
6. Bring up the EDIT dialog for the Plot block and add the following to the "Claims and associated questions" field:
This is an important claim, 7cf9575c53d5abc43fddedc4b06ae1a835dd4bf3, 79020e44630e246077a2bce92f45562fe24769cd
Make sure to replace the two hashes with the question IDs you grabbed in the …
> Step Builder: Support for additional overlays for plot blocks

- problem_builder/mcq.py
- problem_builder/plot.py
- problem_builder/slider.py
- problem_builder/step.py
- problem_builder/templates/html/rating_edit_footer.html
- problem_builder/tests/integration/test_step_builder.py
- problem_builder/tests/integration/xml_templates/step_builder_plot_scale_questions.xml
This PR follows up on #77 and #78 which introduced plot and scale blocks, respectively. More specifically:
1. The changes make sure that plots can access data from scale blocks.
2. The changes make the process for obtaining references to rating and scale blocks consistent in Studio. This means that instead of having to
- bring up the "EDIT" dialog
- scroll down to the "Question ID" field
- copy the contents
course authors can now grab IDs from previews of rating questions:
For scale blocks this behavior was already in place.
**Testing**
1. Add Step Builder to a unit.
2. Add two Mentoring Step blocks and a Review Step block to Step Builder.
3. Add two Scale questions ("Ranged Value Slider") to the first Mentoring Step block.
4. Add a Plot block to the second Mentoring Step block.
5. For …
> Step Builder: Interoperability for scale and plot blocks

- problem_builder/mcq.py
- problem_builder/public/js/questionnaire.js
- problem_builder/tests/integration/base_test.py
- problem_builder/tests/integration/test_mentoring.py
- problem_builder/tests/integration/test_questionnaire.py
- problem_builder/tests/integration/xml/mcq_1.xml
**Description:** MCQ and MRQ were inconsistent in terms of showing feedback: 
* MRQ provided both per-choice feedback and question-level feedback, 
* MCQ, depsite having "message" attribute, only provided per-choice feedback.
1. Create problem builder/step builder with MCQ and MRQ.
2. Fill in "Message" fields for both MCQ and MRQ
3. Provide choices and (optional) tips
4. Open PB/SB in LMS/Apros
5. Answer MRQ. Observe that when feedback is displayed, question-level feedback is shown first, per-choice feedback is available by clicking on correctness icons next to choices
6. Answer MCQ. Observe that the behavior is now the same (i.e. message from "Message" attribute is shown first, per-choice feedback is available by clicking on correctness icon)
If you can't see …
> Making MCQ use message attribute the same way MRQ does

- problem_builder/public/css/problem-builder.css
- problem_builder/public/js/mentoring_with_steps.js
- problem_builder/public/js/step.js
- problem_builder/step.py
- problem_builder/templates/html/step.html
- problem_builder/tests/integration/test_step_builder.py
- problem_builder/tests/integration/xml_templates/step_builder_instruction.xml
To test:
1. Create a step builder block.
2. Add a step to the block.
3. Edit the block. Fill in the message section
4. Add a problem to the block.
5. Save, answer the problem, submit, see new popup thingy. Click anywhere and it should dismiss.
> Add instructional message to step blocks.

- problem_builder/mentoring.py
- problem_builder/mixins.py
- problem_builder/plot.py
- problem_builder/public/css/problem-builder.css
- problem_builder/public/js/container_edit.js
- problem_builder/public/themes/apros.css
- problem_builder/step.py
- problem_builder/step_review.py
- problem_builder/templates/html/mentoring_with_steps.html
- problem_builder/templates/html/sb-review-score.html
This PR fixes the following issues:
* In some Step Builder components, you were unable to change the order of child blocks in Studio (drag-to-reorder was broken). This is due to Studio using a selector that requires the child XBlocks to be direct children of the parent XBlock, with no intermediate elements such as a DIV
* Fixed a minor issue causing mentoring v2 blocks in legacy assessment mode to be broken when tested in Studio.
* Fixed the layout issues in MCKIN-3626
* Added a feature so you can move messages below the "Try Again" button if you want to. To do so, simply do not add a "Per Question Review Tips" block to the review step.
Screenshot of block after fixing layout issues:
Screenshot of block with no per question review step configured:
> Fix a few layout issues in Step Builder

- problem_builder/public/css/problem-builder.css
- problem_builder/public/js/mentoring_with_steps.js
- problem_builder/public/js/plot.js
- problem_builder/public/js/step.js
- problem_builder/public/themes/apros.css
- problem_builder/templates/html/mentoring.html
- problem_builder/templates/html/mentoring_with_steps.html
- problem_builder/tests/integration/test_step_builder.py
- problem_builder/tests/integration/xml_templates/step_builder_long_steps.xml
To test make sure you have `problem-builder` and `imagemodal` (https://github.com/Stanford-Online/xblock-image-modal) xblocks installed. Import latest export (2015.6PFnhS.tar.gz) from OC-1020 into a fresh course.
> Competing Evidence: Fix issues from client QA

- problem_builder/templates/html/sb-review-score.html
- problem_builder/tests/integration/test_step_builder.py
This PR adds a message explaining how to use review links to the "Score Summary" block that can be added to the "Review Step" of a Step Builder exercise.
**Additional info**
- The message is shown if review links are present, and hidden otherwise.
- The wording of the message follows the spec in [MCKIN-3682](https://edx-wiki.atlassian.net/browse/MCKIN-3682).
**Screenshots**
LMS:
Apros:
**Testing**
1. Add Step Builder block to a unit.
2. Add a Mentoring Step and a Review Step to the Step Builder block.
3. Add one or more questions to the Mentoring Step.
4. Add a Score Summary to the Review Step.
5. Set "Max. attempts allowed" to 1 for the Step Builder block.
6. Set "Extended feedback" to "True".
7. Publish.
8. Complete the block in the LMS. Review step should match screenshot above (i.e., …
> Step Builder: Explain review links to users

- problem_builder/migrations/0001_initial.py
Background: Adds Django 1.8 migrations to Problem Builder. The hope is to get this merged into dogwood. Otherwise any installations which use Problem Builder will have to run an extra management command to make their migration data accurate.
@nedbat This is the PR I was talking about. Will we be able to get someone from Platform to give it a look over? @itsjeyd This is ready for you to review-- if you could check it over when you start your day/before I start mine, that would be helpful.
How to test:
1. In MySQL: `CREATE DATABASE edxapp2;GRANT ALL ON edxapp2.* TO 'edxapp001'@'localhost';`
2. Change `cms.auth.json` and `lms.auth.json` to point to the new db, 'edxapp2'.
3. `paver update_db --settings=devstack`
4. Register a new 'staff' user.
5. Lookup and set is_staff on the user via the …
> Create Django migrations, deprecate South.

- .travis.yml
- setup.py
@bradenmacdonald Who would we need to review this? It's needed for https://github.com/edx/edx-platform/pull/11312 All it does is bump the version number.
> Bump version number.

- problem_builder/public/js/mentoring_with_steps.js
After each tap of the 'next' button, the updateDisplay function would be called and apply itself to the next button again, causing exponential rendering runs which would freeze things up after a certain number of questions.
@e-kolpakov This one's a critical hotfix. Please look at it first opportunity, if you can, so we can deploy it Monday.
> Fix exponential rerendering after hitting next button too many times.

- problem_builder/mentoring.py
- problem_builder/public/js/mentoring.js
- problem_builder/public/js/questionnaire.js
- problem_builder/tests/integration/test_mentoring.py
- problem_builder/tests/integration/test_titles.py
- problem_builder/tests/unit/test_problem_builder.py
This PR introduces an instance-wide option to hide previous answers (and feedback) for MCQs in Problem Builder. When this option is enabled, students will still receive per-question feedback after providing answers to MCQs and submitting the containing block, but that feedback will not be visible when they return to the block, and all choices for a given MCQ will be unchecked.
**Screenshots: LMS**
Default settings:
Previous answers hidden:
---
**Screenshots: Apros**
Default settings:
Previous  answers hidden:
1. Create a subsection with two units and add a Problem Builder block to each one.
2. Add a long answer, MCQ, Rating, MRQ, and Slider to one of the Problem Builder blocks.
3. Publish the units.
4. In LMS/Apros, provide answers to all questions and click …
> Problem Builder: Add instance-wide option to hide previous answers for MCQs

- circle.yml
- problem_builder/answer.py
- problem_builder/mentoring.py
- problem_builder/south_migrations/0003_auto__add_share__add_unique_share_shared_by_shared_with_block_id.py
- problem_builder/table.py
- problem_builder/tests/integration/test_assessment.py
- problem_builder/tests/integration/test_author_changes.py
- problem_builder/tests/integration/test_dashboard.py
- problem_builder/tests/unit/test_dashboard_visual.py
- problem_builder/tests/unit/test_problem_builder.py
Follows up on #102.
1. Remove theme settings from `lms.envs.json`.
2. Access unit containing Problem Builder block and check if rules in `public/themes/lms.css` are applied. For example, `.choice-result` should have `display: table-cell` (first rule in `public/themes/lms.css`).
> Ensure default theme is used if theme has not been customized

- problem_builder/mcq.py
- problem_builder/mrq.py
- problem_builder/public/js/questionnaire.js
- problem_builder/questionnaire.py
- problem_builder/tests/integration/base_test.py
- problem_builder/tests/integration/test_answer.py
- problem_builder/tests/integration/test_assessment.py
- problem_builder/tests/integration/test_mentoring.py
- problem_builder/tests/integration/test_questionnaire.py
- problem_builder/tests/integration/test_titles.py
- problem_builder/tests/integration/xml/mcq_1.xml
- problem_builder/tests/integration/xml_templates/feedback_persistence_mcq_no_tips.xml
- problem_builder/tests/integration/xml_templates/feedback_persistence_mcq_tips.xml
Testing instructions: 
Create following MRQ block, and verify that behavior is unchanged: 
1.That when you create submit you get question feedback: "Thank you for answering!" 
2. And after clicking check-mark you get tooltip. 
```
<problem-builder display_name="Default Title" weight="1" mode="standard">
<html_demo>
<p>Please answer the questions below.</p>
</html_demo>
<pb-mrq name="mrq_1_1" question="What do you like in this MRQ?" message="Thank you for answering!" required_choices='["gracefulness","elegance","beauty"]'>
<pb-choice value="elegance">Its elegance</pb-choice>
<pb-choice value="beauty">Its beauty</pb-choice>
<pb-choice value="gracefulness">Its gracefulness</pb-choice>
<pb-choice value="bugs">Its bugs</pb-choice>
<pb-tip values='["gracefulness"]'>This MRQ is indeed very …
```
> OC-1387 Always show tooltips feedback if tips are present.

- problem_builder/mentoring.py
- problem_builder/public/js/answer.js
- problem_builder/public/js/mentoring.js
- problem_builder/public/js/mentoring_standard_view.js
- problem_builder/public/js/mentoring_with_steps.js
- problem_builder/tests/integration/test_mentoring.py
- problem_builder/tests/integration/xml_templates/feedback_persistence.xml
- problem_builder/tests/unit/test_problem_builder.py
This PR introduces an instance-wide option to hide global feedback and results (correct/incorrect) icons for Long Answer blocks in Problem Builder. When this option is enabled (and there are some attempts left), students will still receive global and per-question feedback after providing answers and submitting the containing block, but that feedback will not be visible when they return to the block.
cf. [MCKIN-3858](https://edx-wiki.atlassian.net/browse/MCKIN-3858)
**Screenshots: LMS**
Default settings:
Feedback hidden:
---
**Screenshots: Apros**
Default settings:
Feedback hidden:
1. Create a subsection with two units and add a Problem Builder block to each one.
2. Add a long answer, MCQ, Rating, MRQ, and Slider to one of the Problem Builder blocks.
3. Publish the …
> Problem Builder: Add instance-wide option to hide global feedback and results for Long Answer blocks

- problem_builder/public/js/questionnaire.js
- problem_builder/tests/integration/test_mentoring.py
cf. [MCKIN-3884](https://edx-wiki.atlassian.net/browse/MCKIN-3884)
1. Add Problem Builder block to a unit.
2. Add MCQ block to Problem Builder block.
3. Add a couple of Choice blocks to MCQ block.
4. For each choice, add a Tip block with a unique message.
5. Publish.
6. In LMS/Apros, answer question, click "Submit". Once tip for selected choice is visible, click somewhere else to make tip disappear.
7. Click result icon next to selected choice. Observe that tip becomes visible again.
> Restore functionality for showing choice tips on click

- .travis.yml
- problem_builder/public/js/dashboard.js
- setup.py
The dashboard report image download can currently fail in 2 different ways:
- If the image is from a different domain and it has been cached by the browser, it won't be converted into a data URL due to cross-domain security issues. A javascript `SecurityError` is thrown, and nothing happens.
- If the image url starts with `//` (no explicit protocol) or the url is relative (e.g. `/static/...`), *and* it hasn't yet been cached by the browser, it will fail to show up in the downloaded report.
This pull request fixes both issues, by:
- Not trying to create a data URL for cross-domain requests
- Expanding relative urls and urls without an explicit protocol
> Fix dashboard report image download (edx-release hotfix)

- problem_builder/tests/integration/test_dashboard.py
So that the omar/report-download branch can be deleted
> Use dashboard image from master branch in tests

- problem_builder/public/js/questionnaire.js
- problem_builder/public/js/step.js
- problem_builder/tests/integration/test_step_builder.py
- problem_builder/tests/integration/xml_templates/step_builder_mcq_feedback.xml
cf. [MCKIN-3907](https://edx-wiki.atlassian.net/browse/MCKIN-3907)
1. Create new unit and add StepBuilder block to it.
2. Set "Max. attempts allowed" to `1` and "Extended feedback" to `True` for StepBuilder block.
3. Add MentoringStep block to StepBuilder.
4. Add MCQ block to MentoringStep.
5. Add two Choice blocks to MCQ.
6. Add two Tip blocks to MCQ, one for each Choice (with custom "Content").
7. Add ReviewStep block to StepBuilder.
8. Add ScoreSummary block to ReviewStep.
8. Publish.
9. Complete StepBuilder block in LMS/Apros and "Review grade".
10. Jump back to MCQ by clicking corresponding link. Observe that feedback and result (checkmark) for choice you selected is shown right away.
11. Reload page.
12. Repeat step 10. Observe that feedback and result …
> StepBuilder: Fix inconsistent feedback for MCQs

- problem_builder/mentoring.py
- problem_builder/public/js/answer.js
- problem_builder/public/js/mentoring_standard_view.js
- problem_builder/public/js/mentoring_with_steps.js
- problem_builder/public/js/questionnaire.js
- problem_builder/templates/html/mentoring.html
- problem_builder/templates/html/mrqblock.html
- problem_builder/tests/integration/test_mentoring.py
- problem_builder/tests/unit/test_problem_builder.py
cf. [MKCIN-3890](https://edx-wiki.atlassian.net/browse/MCKIN-3890)
*Test Instructions*
1. Create a new subunit containing one problem builder freeform question unit, and another arbitrary unit.
2. Enable `pb_hide_feedback_if_attempts_remain` in your `XBLOCK_SETTINGS`.
3. Go to the unit with the freeform question, fill it in, and submit.
4. Go to the next unit, then come back to the unit with the freeform question.
5. Feedback should be hidden, but the submit button should be enabled
This PR also contains a patch that makes MRQ behavior when `pb_mcq_hide_previous_answer` option is enable more consistent with the way MCQs behave. To test:
1. Create a new subunit containing one problem builder MRQ question unit, and another arbitrary unit.
2. Enable `pb_mcq_hide_previous_answer` in your …
> Enable freeform answer submit when feedback is hidden

- problem_builder/mentoring.py
- problem_builder/public/js/lms_util.js
- problem_builder/public/js/mentoring_with_steps.js
- problem_builder/public/js/step.js
- problem_builder/public/js/step_util.js
- problem_builder/tests/integration/test_step_builder.py
This is a follow up on: #114 and #112. 
What you need is a course where on a step you have a video, and then you can to the next step (you should still hear the video on that next step --- which is the error). 
1. Create a course with three sections, each containing a single subsection and a single unit. 
2. First unit contains following steps: 
a. A step with Video Block and a question
b. A step with HTML Block with a youtube video and a question. Example embedding code: `<iframe width="420" height="315" src="https://www.youtube.com/embed/QH2-TGUlwu4" frameborder="0" allowfullscreen></iframe>`
c. A step with a question (no videos!)
d. A review step with a HTML with a youtube video, and other review elements. 
3. Second unit contains
a. A step with OOyala video and a question (OOyala …
> Stopping video playback for hidden steps

- problem_builder/mentoring.py
- problem_builder/public/js/questionnaire.js
- problem_builder/tests/integration/test_mentoring.py
- problem_builder/tests/integration/xml_templates/feedback_persistence.xml
- problem_builder/tests/integration/xml_templates/feedback_persistence_mcq_general_feedback.xml
- problem_builder/tests/integration/xml_templates/feedback_persistence_mcq_general_feedback_and_tips.xml
- problem_builder/tests/integration/xml_templates/feedback_persistence_mcq_no_feedback.xml
- problem_builder/tests/integration/xml_templates/feedback_persistence_mrq_general_feedback.xml
- problem_builder/tests/integration/xml_templates/feedback_persistence_mrq_general_feedback_and_tips.xml
- problem_builder/tests/integration/xml_templates/feedback_persistence_mrq_no_feedback.xml
- problem_builder/tests/integration/xml_templates/feedback_persistence_mrq_tips.xml
When the pb_mcq_hide_previous_answer is set to True, question-level feedback should not be displayed when user returns to the page.
cf. [MCKIN-3999](https://edx-wiki.atlassian.net/browse/MCKIN-3999)
*Test Instructions*
1. Create a new subunit containing one problem builder MRQ question unit, and another arbitrary unit. Make sure to put some content into the "Message (General feedback provided when submitting)" field of the MRQ.
2. Enable `pb_mcq_hide_previous_answer` in your `XBLOCK_SETTINGS`.
3. Go to the unit with the MRQ question, fill it in, and submit. You should see the general feedback message.
4. Go to the next unit, then come back to the unit with the MRQ question.
5. General feedback message should be hidden.
> Hide MRQ question-level feedback on return.

- .travis.yml
- problem_builder/answer.py
- problem_builder/step.py
- problem_builder/table.py
- setup.py
This fixes https://openedx.atlassian.net/browse/TNL-4901 by backporting the already-existing fix that was on the `master` branch.
The problem was that `mentoring_view` was inadvertently modifying its `context` parameter.
Note 1: @adampalay tested and confirmed this fixes the TNL-4901 issue.
Note 2: on this branch, CircleCI is expected to fail (it's only configured on master), but TravisCI is required to pass - so the tests are fine.
> Fix mako template context error

- circle.yml
- requirements.txt
New version includes fixes from https://github.com/edx/xblock-utils/pull/38 and https://github.com/edx/xblock-utils/pull/39.
Follow-up PR for [OC-1819](https://tasks.opencraft.com/browse/OC-1819) (candidate task).
Also fixes an issue affecting dependency installation for CircleCI builds for problem-builder. See the commit message of https://github.com/open-craft/problem-builder/pull/120/commits/51277a34fb426724616618c1afdb893ab2de4c6b for details.
> Update xblock-utils to v1.0.3.

- problem_builder/mentoring.py
- problem_builder/message.py
- problem_builder/public/css/problem-builder-edit.css
- problem_builder/public/css/questionnaire-edit.css
- problem_builder/questionnaire.py
- problem_builder/templates/html/mentoring_add_buttons.html
- problem_builder/templates/html/questionnaire_add_buttons.html
Removes the ability for Studio users to add `Message (Assessment Review)` components to Problem Builder units, unless the legacy "assessment mode" is enabled.
Studio users may still add `Message (Review)` components to Step Builder Questionnaire components, and to legacy "assessment mode" Problem Builder Questionnaire components, but not to new Problem Builder units.
Also fixes the style issues these buttons by allowing the buttons to use `width: auto` and `height: auto` to accommodate varied text lengths.
**Screenshots**:
* `Message (Assessment Review)` removed from Problem Builder:
* `Message (Assessment Review)` style fixed in Problem Builder (legacy assessment mode):
* `Message (Assessment Review)` removed from Problem Builder Questionnaires:
* `Message (Assessment Review)` style …
> Remove "Message (Assessment Review)" from Problem Builder in Studio

- problem_builder/tasks.py
In some cases it is possible that the anonymous `student_id` of a submission can't be reversed to the original user.  In this case, the function `user_by_anonymous_id()` returns `None`, resulting in a crash when building reports.
This change fixes the crash by returning `student_id` instead of the actual user name in case it cannot be reconstructed.
> Handle unresolvable anonymous ids gracefully.

- problem_builder/public/css/instructor_tool.css
- problem_builder/public/css/plot-preview.css
- problem_builder/public/css/problem-builder.css
- problem_builder/public/css/questionnaire.css
- problem_builder/public/js/answer.js
- problem_builder/public/js/mentoring_assessment_view.js
- problem_builder/public/js/mentoring_with_steps.js
- problem_builder/public/js/questionnaire.js
- problem_builder/public/themes/lms.css
- problem_builder/templates/html/answer_editable.html
- problem_builder/templates/html/instructor_tool.html
- problem_builder/templates/html/mcqblock.html
- problem_builder/templates/html/mentoring_with_steps.html
- problem_builder/templates/html/mrqblock.html
- problem_builder/templates/html/plot_preview.html
- problem_builder/templates/html/ratingblock.html
- problem_builder/templates/html/slider.html
- problem_builder/templates/html/step.html
- problem_builder/tests/integration/test_mentoring.py
- problem_builder/tests/integration/test_questionnaire.py
- problem_builder/tests/integration/test_step_builder.py
Addresses the following accessibility issues:
* Encloses all `<input>` and `<textarea>` fields inside a `<label>`, as per edx-platfomr's CAPA problem layout.
* Associates question and feedback text with the corresponding choice labels, matching edx-platform's CAPA problem layout.
* Ensures that all `<input>` elements have a `<label>`.
* Ensures all table header cells use `<th>` elements.
* Associates feedback icons and choice-level feedback messages with the corresponding choice.
* Adds `aria-live="polite"` attributes to the blocks whose content changes without page reload.
**Partner information**: affects edX-hosted clients who use this XBlock.
1. Install this PR's branch of the problem-builder xblock on your devstack.  (Ensure that any other versions are …
> Accessibility updates

- circle.yml
- problem_builder/instructor_tool.py
- problem_builder/tasks.py
- problem_builder/tests/integration/test_instructor_tool.py
- setup.py
Fixes celery task error (ref [TNL-5903](https://openedx.atlassian.net/browse/TNL-5903)):
> RuntimeError: Conflicting 'instructortask' models in application 'instructor_task': <class 'lms.djangoapps.instructor_task.models.InstructorTask'> and <class 'instructor_task.models.InstructorTask'>.
*Testing instructions*
1. Ensure your devstack is updated to current `master`.  The commit that introduced the conflict was [54d34e8](https://github.com/edx/edx-platform/commit/54d34e834d5a108f03db59a1e0f6b97e2afae7d0).
1. Create a course, and import [course.99Ob05.tar.gz](https://github.com/open-craft/problem-builder/files/575891/course.99Ob05.tar.gz).
1. Visit the Features > Instructor Tool unit, and note that you're able to filter and download data.
*Reviewers*
> Uses the same import path for instructor_task.models as edxapp

- circle.yml
- problem_builder/answer.py
- problem_builder/instructor_tool.py
- problem_builder/public/js/instructor_tool.js
- problem_builder/questionnaire.py
- problem_builder/templates/html/instructor_tool.html
- problem_builder/tests/unit/test_instructor_tool.py
- setup.py
Moves the logic that populates the Instructor Tool's drop-down list of course blocks out of the server-side and into the client, using the Course Blocks API as the data source.
**Discussions**: In [#119](https://github.com/open-craft/problem-builder/pull/119#discussion_r85763360), @ormsbee raised concerns about performance and maintainability of the old server-side mechanism for traversing the course blocks via the runtime object's parents.
**Sandbox URL**: 
* LMS: http://pr13953.sandbox.opencraft.hosting (persistent databases)
* Studio: http://studio-pr13953.sandbox.opencraft.hosting
**Partner information**: DavidsonX
1. Ensure your devstack is updated to current `master`.
1. Install the previous version of Problem Builder, …
> 2.6.2 Instructor Tool uses the Course Blocks REST API

- circle.yml
- problem_builder/migrations/0003_auto_20161116_0730.py
- problem_builder/models.py
- setup.py
This patch extends the `course_id` column to 255 characters.
Previous limit of 50 characters was too low, causing 500 errors when adding the 'Long Answer' block to a course with a course key extending 50 characters.
**JIRA ticket**: [TNL-5932](https://openedx.atlassian.net/browse/TNL-5932)
**Partner information**: DavidsonX
Steps to reproduce:
1. Install problem-builder xblock without this patch (v2.6.2).
1. Create a new course with a long course key in Studio (choose long organization, course number and course run fields, for example: "VeryLongOrganizationName", "VeryLongCourseName", "VeryLongCourseRun2016")
1. Add "problem-builder" to list of advanced modules in advanced settings.
1. Create a new unit and add a 'Problem Builder' block.
1. Add 'Long Answer' …
> Extend course_id field to 255 characters.

- circle.yml
- problem_builder/answer.py
- problem_builder/migrations/0003_auto_20161124_0755.py
- problem_builder/models.py
- problem_builder/tests/unit/test_answer_mixin.py
- setup.py
This patch introduces a new 255-char `course_key` field to the `Answer` model. The old 50-char `course_id` field is still present, but is deprecated and will be removed in next release.
It removes the previous migration (which was never deployed to production) which extended the existing `course_id` field to 255 characters, which was found to not be the optimal approach on the edx.org production database due to the relevant table's size. We cannot simply extend the existing `course_id` field because we have some large `problem_builder_answer` tables in production and the migration to extend the column would lock the table causing issues in production.
The code is updated so that it uses the new `course_key` column, but falls back to `course_id`.
In next release, a data migration to copy …
> Introduce Answer.course_key and deprecate course_id.

- problem_builder/public/js/questionnaire.js
This PR fixes a bug where tip and result icon is not appeared on review step when two MCQ questions in a step build share two same choices.
To reproduce the issue
1.  import [sample course](https://github.com/open-craft/problem-builder/files/616223/2016.nQWXtB.tar.gz)
2.  Enroll in newly imported course and attempt Sport Quiz -> Football Quiz
3.  Select **Baltimore Colts** for first Question and **Atlanta Falcons** for second question
4.  On Review step click **Question 2**. You'll neither be able to see a red cross before **Atlanta Falcons** nor a tip next to it.
@bradenmacdonald can you assign are reviewer to this?
> YONK-476: fixed review step not showing tip and result icon

- circle.yml
- problem_builder/answer.py
- setup.py
This is a follow-up to #131, addressing https://github.com/open-craft/problem-builder/pull/131#pullrequestreview-10605706
**Environments**:  edx.org and edge.edx.org
**Merge deadline**: ASAP - this is blocking a course on Edge
**JIRA tickets**: [TNL-5932](https://openedx.atlassian.net/browse/TNL-5932)
**Discussions**: https://github.com/open-craft/problem-builder/pull/131#pullrequestreview-10605706
**Sandbox URL**:
Note that this is the same sandbox instance that was used for #131, but was updated to use this branch of problem problem-builder. Version currently installed on the sandbox is e502a5565105571ab0303c330dc1a06036a7816f.
- LMS: http://pr14044.sandbox.opencraft.hosting/
- Studio: http://studio-pr14044.sandbox.opencraft.hosting/
**Partner information**: hosted on edX Edge (Davidson …
> Use django Q objects instead of raw SQL query

- README.md
Updates README to:
* Add Open edX installation instructions
* Note the incompatibility issue between `v2.6.1` and Eucalyptus
* Provide guidance on compatibility with other versions of `edx-platform`.
**Reviewers**
> Updates README to note tag compatibility with edx-platform

- circle.yml
- problem_builder/answer.py
- problem_builder/migrations/0004_copy_course_ids.py
- problem_builder/migrations/0005_auto_20170112_1021.py
- problem_builder/models.py
- problem_builder/tests/unit/test_answer_mixin.py
- setup.py
This is a follow-up to #131. In #131, we deprecated the `Answer.course_id` field and replaced it with a new `Answer.course_key` field with extended length to accommodate courses with course keys longer than 50 characters (for example some CCX courses on edx.org have course keys longer than 50 characters).
This PR includes a migration that copies contents of `course_id` column into `course_key`, for any `Answer` object where `course_key` is `NULL` (these are `Answer` objects that were created before problem-builder v2.6.5 was deployed).
**NOTE: Before deploying v2.6.6 to production, edX will have to fake this migration and manually copy `course_id` values into `course_key` in batches because the production `problem_builder_answer` table is large and performing the migration in one go would …
> Copy course_id into course_key and remove temporary transition code

- problem_builder/public/css/questionnaire.css
- problem_builder/public/js/questionnaire.js
- problem_builder/templates/html/mcqblock.html
- problem_builder/templates/html/mrqblock.html
- problem_builder/templates/html/ratingblock.html
Reported by McKinsey.
cf. [OC-2264](https://tasks.opencraft.com/browse/OC-2264)
**Screenshots** (Apros)
MCQ:
MCQ during review (with tip):
Rating question:
Rating question during review (without tip):
MRQ:
MRQ during review (without tip):
1. Add a Step Builder block to a unit, setting "Max. attempts allowed" to a non-zero value, and "Extended Feedback" to True.
2. Add a Mentoring Step block and a Review Step block to the Step Builder block.
3. Add an MCQ, Rating, and MRQ to the Mentoring Step block, setting the text of some choices to a long string.
4. Add tips for individual choices to the MCQ.
5. Add a Score Summary block to the Review Step block.
6. Publish the unit and navigate to it in the LMS/Apros. Observe that alignment of choice texts matches screenshots.
7. …
> Fix display of MCQ/MRQ choices with long text.

- problem_builder/public/js/completion.js
- problem_builder/tests/integration/test_mentoring.py
- problem_builder/tests/integration/xml_templates/feedback_persistence.xml
This makes the Completion block consistent with the Answer block.
When 'pb_hide_feedback_if_attempts_remain' is set to True in
XBLOCK_SETTINGS, once the user submits an answer to an Answer (freeform
long answer), the green checkmark is not visible after refreshing the
page, even though the given answer/text is still visible.
This commit makes Completion blocks consistent with that behaviour.
**JIRA ticket**: https://edx-wiki.atlassian.net/browse/MCKIN-4707
**Reviewers**:
> Do not show completion checkmark when hide_feedback is enabled

- problem_builder/public/themes/apros.css
... to incorporate feedback from QA team (cf. https://github.com/open-craft/problem-builder/pull/139#issuecomment-277910917).
Follows up on #139.
**Screenshots: Apros**
Problem Builder:
Step Builder:
**Screenshots: LMS**
Problem Builder:
Step Builder:
1. Make sure you're using the Apros theme. In `lms.env.json`:
```json
"XBLOCK_SETTINGS": {
"mentoring": {
"theme": {
"package": "problem_builder",
"locations": ["public/themes/apros.css"]
},
```
2. Add MCQs and MRQs with long choice texts to a Problem Builder block.
3. Access Problem Builder block in Apros. Observe that layout of choices matches screenshot above.
4. Repeat previous steps for a Step Builder block.
5. Switch to LMS theme:
```json
"XBLOCK_SETTINGS": {
"mentoring": {
"theme": {
"package": "problem_builder", …
```
> Override layout of choice label in Apros theme

- circle.yml
- problem_builder/management/commands/copy_deprecated_course_id.py
- setup.py
Normally the value of deprecated `Answer.course_id` will be copied into the new `Answer.course_key` field by a migration, but if your answer table is very large, you might want to use this management command to perform the copying in batches instead.
The new management command added by this patch lets you copy the column in batches, with a configurable batch size and sleep time between each batch.
**Discussion**: https://github.com/edx/edx-platform/pull/14327#issuecomment-280043022
1. Install this branch of problem builder. Add some Answer type blocks to a unit in studio and fill them in the LMS to populate some entries in the `problem_builder_answer` table.
2. Current release of problem builder does not allow `NULL` values in the `course_key` field, so you'll …
> Add management command to manually migrate course_id field.

- problem_builder/public/css/problem-builder.css
- problem_builder/public/themes/apros.css
- problem_builder/templates/html/answer_editable.html
- problem_builder/templates/html/answer_read_only.html
- problem_builder/templates/html/completion.html
- problem_builder/templates/html/dashboard.html
- problem_builder/templates/html/instructor_tool.html
- problem_builder/templates/html/mcqblock.html
- problem_builder/templates/html/mentoring.html
- problem_builder/templates/html/mentoring_assessment_templates.html
- problem_builder/templates/html/mentoring_with_steps.html
- problem_builder/templates/html/mrqblock.html
- problem_builder/templates/html/overlay.html
- problem_builder/templates/html/plot.html
- problem_builder/templates/html/ratingblock.html
- problem_builder/templates/html/sb-review-score.html
- problem_builder/templates/html/slider.html
- problem_builder/templates/html/step.html
- problem_builder/tests/integration/base_test.py
- problem_builder/tests/integration/test_titles.py
- problem_builder/v1/tests/xml/v1_upgrade_b_new.xml
- problem_builder/v1/tests/xml/v1_upgrade_b_old.xml
- setup.py
As discussed with @pomegranited , have had a first pass at amending headings within the templates to allow for the heading structure change from Eucalyptus. For the most part it's just bumping them down a level, with one being bumped down from 2 to 4 (as unless it's not the element I'm thinking of, its heading level was too high to begin with).
Note that there's references to other H2+H3's etc. contained within things like the python tests that I've not touched, so presumably those will fail and also need updating, I just didn't want to mess with anything I don't understand. I've also not amended the apros theme CSS. Basically, half the task still to do.
> Heading restructure

- circle.yml
- problem_builder/management/commands/copy_deprecated_course_id.py
- setup.py
This modifies the management command introduced in https://github.com/open-craft/problem-builder/pull/143 to avoid a `COUNT(*)` query for performance reasons.
**Testing instructions**: Please see https://github.com/open-craft/problem-builder/pull/143
**Reviewers**:
> Avoid count(*) query in management command.

- problem_builder/answer.py
It will be useful to be able to get the names of all answer blocks in a course via the Course API.
See http://edx.readthedocs.io/projects/edx-platform-api/en/latest/courses/index.html for information on how Course API and `student_view_data` method work together.
**Testing**:
1. Install this branch into your edx-platform virtual environment.
1. Add a problem builder block with a freeform answer child to a course.
1. Verify that you can see the answer block's name attribute in the output of the Course API if you specify `fields=student_view_data` and `student_view_data=pb-answer` parameters. The full URL should look like this: http://my.edx.local/api/courses/v1/blocks/?course_id=my/course/key&all_blocks=true&depth=all&fields=student_view_data&student_view_data=pb-answer
**Reviewers**:
> Add 'name' attribute to AnswerBlock's student_view_data.

- problem_builder/mcq.py
- problem_builder/mentoring.py
- problem_builder/tests/unit/test_problem_builder.py
This PR adds `student_view_data` methods to the Problem Builder and MCQ blocks so their data can be exported as JSON and queried through the Courses API.
**Testing instructions**
1. Install this branch into your edx-platform virtual environment.
2. In Studio, as `staff`, add a Problem Builder block to the demo course and set the following attributes:
- Max. attempts allowed
- Feedback Header
- extended_feedback
3. Check the ID of the block in the message:
`url_name for linking to this mentoring question set: ...`
4. Add a Multiple Choice Question to the PB Block setting the following attributes:
- Question
- Weight
-  Message
5. Add a few choices to the Multiple Choice Question, setting tips for some of them.
6. Add one of each type of message to the PB Block (Complete, Incomplete, Max # …
> Add API for native mobile Problem Builder + MCQ view to Problem Builder

- problem_builder/dashboard.py
- problem_builder/mentoring.py
Since the block is already mostly usable on mobile, this PR will enable mobile views. Over time we will work to improve the responsiveness of each webview version.
Testing notes: This was already tested by the McKA QA team on MCKIN-5241 since this branch was deployed to the QA server for a while. See that ticket for details. To test manually, install this on devstack then build the edX iOS or Android app and confirm that problem builder is usable on mobile.
> Enable mobile support

- problem_builder/answer.py
- problem_builder/choice.py
- problem_builder/completion.py
- problem_builder/mcq.py
- problem_builder/mentoring.py
- problem_builder/mrq.py
- problem_builder/plot.py
- problem_builder/questionnaire.py
- problem_builder/slider.py
- problem_builder/step.py
- problem_builder/step_review.py
- problem_builder/tests/unit/test_step.py
- problem_builder/tests/unit/test_step_builder.py
- run_tests.py
This PR adds is prototype to return `student_view_data` from Mentoring Blocks.
**Testing**
1. Setup a course with `xblock-problem-builder`
2. Add a `step-builder` block to the course
3. Add 2+ mentoring steps and 1+ review steps.
4. For each step, add a few items (try to cover one of each at least).
5. Log to LMS as the `staff` user.
6. Go to http://localhost:8000/api/courses/v1/blocks/<block id>?all_blocks=true&depth=all&requested_fields=student_view_data [1]
7. Check the data returned in the `student_view_data` fields. Make sure they are sufficient and make sense. 
[1] Replace `<block id>` with the block's id. You can get it using something like the command below:
```
http 'localhost:8000/api/server/courses/course-v1:<course>?depth=5' 'X-Edx-Api-Key: edx_api_key'
```
**Reviewers**
> Add student_view_data to step builder

- circle.yml
- problem_builder/models.py
- setup.py
This PR simply adds `app_label`s to the problem-builder Answer and Share models (and silences Django deprecation warnings).
**JIRA tickets**: Implements [OC-2856](https://tasks.opencraft.com/browse/OC-2856), [PLAT-1644](https://openedx.atlassian.net/browse/PLAT-1644).
**Dependencies**: None
**Sandbox URL**: TBD - sandbox is being provisioned.
**Deployment targets**: edx.org and edge.edx.org
**Merge deadline**: ASAP
1. Ensure that the [problem-builder](https://github.com/open-craft/problem-builder) XBlock is installed and running on Studio
2. Check console output and check for absence of the following deprecation warnings:
```
2017-08-04 04:28:57,685 WARNING 23527 [py.warnings] base.py:116 - /edx/src/problem-builder/problem_builder/models.py:59: …
```
> [OC-2856] Fixed deprecation warnings for the Answer and Share models

- problem_builder/answer.py
- problem_builder/choice.py
- problem_builder/completion.py
- problem_builder/mcq.py
- problem_builder/mentoring.py
- problem_builder/mixins.py
- problem_builder/mrq.py
- problem_builder/slider.py
- problem_builder/step.py
- problem_builder/tests/unit/test_answer_mixin.py
- problem_builder/tests/unit/test_mixins.py
- problem_builder/tests/unit/utils.py
**Description:** This PR adds is prototype to return `student_view_data` from Mentoring Blocks.
**Testing**
1. Import [PB demo course](https://github.com/open-craft/demo-courses/tree/problem-builder)
2. Log to LMS as the `staff` user.
3. Go to http://localhost:8000/courses/:course_id/:block_id/handler/student_view_user_state
4. Check the data returned in the `student_view_user_state` fields. Make sure they are sufficient and make sense.
*Getting block ID*:
Two options:
1. http://localhost:8000/api/courses/v1/blocks/?course_id=course-<course_id>&depth=all&all_blocks=true = manual search
2. Open target block in studio, note the URL
> [MCKIN-5253] - Student_view_user_data

- problem_builder/mrq.py
This PR extend's the MRQ XBlock to include choices and tips in `student_view_data` output.
**JIRA tickets**: [OC-2874](https://tasks.opencraft.com/browse/OC-2874)
**Dependencies**: None
**Merge deadline**: None
1. Have a local course with an MRQ, or import the attached course.
2. Find that course ID
3. Go to http://localhost:8000/api/courses/v1/blocks/?all_blocks=true&depth=all&requested_fields=student_view_data&course_id=<course_id>
4. See that there are values for `choices` and `tips` in `student_view_data` for the MRQ.
**Reviewers**
> [OC-2874] Added choices and tips to MRQ student_view_data

- doc/Native APIs.md
- problem_builder/completion.py
- problem_builder/mentoring.py
- problem_builder/plot.py
- problem_builder/slider.py
- problem_builder/step_review.py
- problem_builder/tests/unit/test_step_builder.py
This documents `student_view_data`, `student_view_user_state`, and custom handlers for each supported component.
**Notes and Concerns**:
The APIs are not very consistent between some components. Some APIs consume data in weird shape, most notably [freeform answer submit handler](https://github.com/open-craft/problem-builder/blob/502d6eeea33a364261ee36c3e5dcbd40134ec0f1/doc/Native%20APIs.md#post-submit-data), probably because it was never designed to be public.
Currently `components` entry in `student_view_user_state` is a dict where keys edX block keys (i.e. `'i4x://TstCrs/TS111/pb-answer/a0b04a13d3074229b6be33fbc31de233'`), but in `student_view_data` we typically use our internal customizable unique IDs (`self.name`).
We might want to make that more consistent.
I don't like how we simply …
> Add docs about API methods which can be used form native apps

- problem_builder/tests/unit/test_problem_builder.py
As @mtyaka and I have discussed, it's difficult to test `student_view_data` methods because:
> complex block hierarchies are hard to set up in tests (see the [test for step builder](https://github.com/open-craft/problem-builder/blob/d191a0e7559207155ba6af56b444048f1ad2d39a/problem_builder/tests/unit/test_step_builder.py) for example), and because the APIs haven't stabilized yet.
To avoid relying on the deprecated`XBlock.field_data` to populate a block's data, I've avoided it completely and written a simple test to ensure that at least the correct keys are always returned by `MRQBlock.student_view_data()`.
**JIRA tickets**: Part of [OC-2874](https://tasks.opencraft.com/browse/OC-2874)
**Merge deadline**: None
1. Inside the problem-builder repo root and appropriate …
> Add simple test for MRQ student_view_data 

- circle.yml
- doc/Native APIs.md
- problem_builder/answer.py
- problem_builder/mcq.py
- problem_builder/public/js/answer.js
- problem_builder/public/js/questionnaire.js
- setup.py
Originally the submission was of the following form:
- For MCQ (multiple-choice questions) it was string value.
- For long/free form answers, it was a json in an array [{<key>: <answer string>}]
This PR makes the submission for both MCQs and freeform answers to the same format, a json with a 'value' key ({"value": <answer string>}). This is so that we can add other info if needed in future.
> OC-2959 freeform and MCQ submitted values are a json and not an array

- doc/Native APIs.md
- problem_builder/answer.py
- problem_builder/choice.py
- problem_builder/completion.py
- problem_builder/mcq.py
- problem_builder/mentoring.py
- problem_builder/mixins.py
- problem_builder/mrq.py
- problem_builder/plot.py
- problem_builder/slider.py
- problem_builder/step.py
- problem_builder/step_review.py
- problem_builder/tests/unit/test_answer_mixin.py
- problem_builder/tests/unit/test_mixins.py
- problem_builder/tests/unit/test_problem_builder.py
- problem_builder/tests/unit/test_step_builder.py
- problem_builder/tip.py
- setup.py
This PR adds a way to allow developers to manually control what fields eventually appear in `student_view_user_state` via `build_user_state_data` by specifying attributes on XBlocks that inherit from `StudentViewUserStateMixin`
**JIRA tickets**: [OC-2958](https://tasks.opencraft.com/browse/OC-2958)
**Dependencies**: None
**Merge deadline**: None
**student_view_user_state**
1. When viewing an XBlock's `student_view_user_state` (e.g. http://localhost:8000/courses/<course_id>/xblock/<xblock_usage_id>/handler/student_view_user_state), modify fields by adding field names to the block's `USER_STATE_FIELDS` or field name -> function to `USER_STATE_TRANSFORMS`
2. See them appear in the JSON output
**student_view_data**
1. When viewing a course's `student_view_data`, …
> define ways to filter and map xblock features into build_user_state_data

- problem_builder/public/js/instructor_tool.js
- problem_builder/tasks.py
This fixes the Instructor Tool in Apros which was raising a `Could not find the specified block ID` error.
1. It removes a block ID manipulation from the JS code that was causing bugs in the backs for all IDs without a `block@` substring, like the Apros' ones (e.g. `i4x://132re3fe2oif...`).
2. It looks up the block by UsageKey rather than a selector, making it work for all IDs.
**JIRA ticket**: [OC-2998](https://tasks.opencraft.com/browse/OC-2998)
1. Check that the Instructor Tool in Apros exports HTML and CSV reports.
2. Check that the source block filter works correctly.
3. Check that the Instructor Tool still works with the regular devstack.
> Fix Instructor Tool in Apros

- problem_builder/instructor_tool.py
- problem_builder/mrq.py
- problem_builder/public/js/instructor_tool.js
- problem_builder/tasks.py
- problem_builder/tests/unit/test_instructor_tool.py
This extends the Instructor Tool module to:
* Add support for MRQ in the HTML and CSV reports.
* Add user ID and user email columns to the CSV report.
**JIRA ticket**:  [OC-2997](https://tasks.opencraft.com/browse/OC-2997)
1. Add a couple of MRQ in a problem builder xblock
2. Submit answer(s) with a few users
3. Verify in the Instructor Tool that MRQs are filterable in the dropdown 
4. Make sure MRQs are displayed in the HTML table and included in the CSV export
5. Make sure user IDs and user emails are included in the CSV export but not in the HTML table
**Considerations**:
When choosing a MCQ filter in the Instructor Tool, also Rating questions (a subclass of MCQ) are listed. I'm assuming this is desired behaviour because technically ratings are also MCQ?
> Support for MRQ, user ID and user e-mail in Instructor Tool

- doc/Native APIs.md
- problem_builder/answer.py
- problem_builder/choice.py
- problem_builder/completion.py
- problem_builder/mcq.py
- problem_builder/mentoring.py
- problem_builder/mrq.py
- problem_builder/plot.py
- problem_builder/slider.py
- problem_builder/step.py
- problem_builder/step_review.py
- problem_builder/tests/unit/test_problem_builder.py
- problem_builder/tests/unit/test_step_builder.py
- problem_builder/tip.py
- setup.py
**Description:** This PR adds `display_name` field to `student_view_data`.
**Author concerns:**
1. `student_view_data` is added as a method individually to each XBlock that needs it - there are no common base method - not fixing this due to being out of scope and lack of time.
1. `student_view_data` test coverage is quite superfluous - just a handful of blocks are checked - not fixing this due to being out of scope and lack of time.
1. Some XBlocks already provided `display_name` field via `title` key - not changing `title` as it is likely used by the clients and still adding `display_name` to provide a common denominator to all XBlocks.
**Merge deadline:** Monday, 2017-09-18.
**Testing:**
0. Install this version
1. Create a course with Problem builders (or just import from OpenCraft demo …
> Student view data with display names

- doc/Native APIs.md
- problem_builder/mentoring.py
- problem_builder/mixins.py
- setup.py
Includes the data used to populate Review Step HTML pages in the data returned by the Step Builder's XBlock handler `student_view_user_state`.
This data is stored in the `score_summary` object, and includes any `review_tips` recommended for display for incorrect question responses.
**JIRA tickets**: MCKIN-6092, OC-3172
**Sandbox URL**: sandbox is being provisioned.
* LMS: https://pb_pr171.sandbox.opencraft.hosting/
* Studio: https://studio-pb_pr171.sandbox.opencraft.hosting/
1. In Studio, import this test course: [course.MCKIN-6092.tar.gz](https://github.com/open-craft/problem-builder/files/1358084/course.MCKIN-6092.tar.gz)
Note the course ID for the following steps.
1. Navigate to the Step Builder unit in the LMS.  Don't attempt any problems yet.
1. In the JS …
> MCKIN-6092 Adds score_summary and review_tips to Step Builder student_view_user_state data

- doc/Native APIs.md
- problem_builder/mentoring.py
- problem_builder/public/css/problem-builder.css
- problem_builder/public/js/questionnaire.js
- problem_builder/swipe.py
- problem_builder/templates/html/swipeblock.html
- setup.py
This PR creates a new component type for Binary Choice Questions, which will be utilized for a swiping mobile interface.
**JIRA tickets**: Implements OC-3175, MCKIN-5975
1. Add a new problem builder component.
2. Add a new "Swipable Binary Choice Question" sub-component
3. Add a two possible choices, and mark one as correct.
**Reviewers**
**Settings**
Under `/admin/xblock_django/xblockconfiguration`, an option named "pb-swipe" must be created and enabled.
> Add SwipeBlock for swipeable binary choice questions

- problem_builder/public/js/mentoring_with_steps.js
- problem_builder/templates/html/sb-review-score.html
- problem_builder/tests/integration/test_step_builder.py
- setup.py
**Description:** This PR makes use of [Apros API](https://github.com/mckinseyacademy/mcka_apros/pull/1834) to submit interactions to SCORM shell
Mechanism employed s pretty generic (submitting JS XBlock event) and not tied to Apros.
**Dependecies:** Self-contained, but effect can be only seen by applying https://github.com/mckinseyacademy/mcka_apros/pull/1834
0. Create a course with Step Builder and have a review step in it. Make sure some questions are graded to test submitting correct grade, and number of attempts is limited.
1. In Apros complete the problem and go to review step
1.1. Expected result: [this line](https://github.com/mckinseyacademy/mcka_apros/pull/1834/files#diff-cc7ad4bcad263f3c78f2d38e62d5be9cR300) is hit and `interaction_data` carries correct …
> Emit interactions

- problem_builder/public/js/mentoring.js
- problem_builder/public/js/mentoring_assessment_view.js
- problem_builder/public/js/mentoring_standard_view.js
- setup.py
**Description:** This PR makes use of [Apros API](https://github.com/mckinseyacademy/mcka_apros/pull/1834) to submit interactions to SCORM shell from outdated "mentoring" problem builder.
Mechanism employed s pretty generic (submitting JS XBlock event) and not tied to Apros.
**Author concerns:** support for "assessment" mode is reduced in latest version of problem builder - it is not possible to create an atssessment mentoring block anymore. In this PR, assessment mode is also affected, but it is not possible to test the changes without existing course with "assessment" mode PR. Unfortunately, I don't have one, so I was unable to test assessment mmode
**Dependecies:** Self-contained, but effect can be only seen by applying https://github.com/mckinseyacademy/mcka_apros/pull/1834
**Testing …
> Adding support for notifying interactions to "mentoring" problem builder

- circle.yml
Migrating to CircleCI version 2.
JIRA Ticket: OC-4053
Testing instructions:
Check that tests are passing.
Note to reviewer:
- Had to upgrade to python version 2.7.14, since 2.7.10 is not in the list of docker images: https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/python/images.
- Installing firefox, since it doesn't come with the environment anymore.
- Added cache for python requirements
Reviewers:
[Sven]
> Migrate to CircleCI v2

- doc/Native APIs.md
- doc/Questions.md
- doc/Usage.md
- problem_builder/swipe.py
- setup.py
This PR allows instructors to specify feedback content to be displayed when students provide correct or incorrect answers. 
1. Manually enable the ``pb-swipe`` block by adding an X block configuration in the studio admin at {STUDIO_URL}/admin/xblock_django/xblockconfiguration/ . The name should be ``pb-swipe`` and it should be set to enabled. 
2. Add a Problem Builder unit and you should see a "Swipeable Binary Choice Question" block.
3. Add the block, edit and fill in the desired values. Note the addition of "Correct answer feedback" and "Incorrect answer feedback". 
4. Publish the unit. 
5. The block and the new feedback fields should now be visible in the Course Blocks API via:
{LMS_URL}/api/courses/v1/blocks/?course_id=<course_id>&username=staff&depth=all&stud …
> [MCKIN-7199] Add feedback for swipe component

- doc/Native APIs.md
- problem_builder/answer.py
- problem_builder/tests/unit/test_problem_builder.py
- setup.py
This PR adds the ``description`` field to the ``student_view_data`` for the "Long Answer Recap" XBlock so it can be consumed via APIs. 
1. Install this branch of problem-builder in LMS and Studio
2. Create a "Long Answer" block
3. Create a "Long Answer Recap" block linked to the above
4. Use the course blocks API to fetch the block data for the block using:
``http://localhost:18000/api/courses/v1/blocks/BLOCK_LOCATION/?all_blocks=true&student_view_data=pb-answer-recap``
5. You should see a response like:
```json
{
"root": "block-v1:opencraft+oc101+2018_1+type@pb-answer-recap+block@3c4f7c1c3a2445dd9d28930f582ccec5",
"blocks": {
"block-v1:opencraft+oc101+2018_1+type@pb-answer-recap+block@3c4f7c1c3a2445dd9d28930f582ccec5": {
"display_name": "Recap d139b8d", …
```
> Add description field to student_view_data for long answer recap block

- problem_builder/public/css/questionnaire.css
- setup.py
- Fixed feeback close button direction from right to left
**Steps to test the change:**
- Select an option from MCQ/MRQ and click submit
- Feedback close button should be on left in RTL
> Fixed feedback close button in RTL

- problem_builder/swipe.py
- problem_builder/tests/unit/test_swipe.py
- setup.py
When adding a "Swipe" component to problem builder in Studio, if the author leaves the default value of:
then the student_view_data API will include:
"correct": null
instead of the expected value of
"correct": false
This PR fixes it. Note that NULL values should never have actually been saved into mongodb, so there's no concern over backwards compatibility. This only affects blocks where the field value wasn't saved at all.
**Testing instructions**
1. Make sure [the swipe component is enabled](https://github.com/open-craft/problem-builder/blob/master/doc/Questions.md#swipeable-binary-choice-question).
2. Create/find a course containing a problem builder with a swipe component. Leave the default "correctness" value unchanged.
3. Check [the student_view_data …
> Fix: default 'correctness' of swipe is null, not false (MCKIN-7547)

- circle.yml
- setup.py
This bumps the version and attempts to set up automated PyPI uploads via CircleCI following the advice in [their blog post on the topic](https://circleci.com/blog/continuously-deploying-python-packages-to-pypi-with-circleci/):
* Removed an obsolete pin on an old version of setuptools (the referenced bug was long since fixed)
* Added a deployment job.
* Only run the deployment job for git tag pushes, and only if the build job for the same push succeeds.
Before the automatic uploads will work, you need to add the `PYPI_PASSWORD` environment variable to the CircleCI settings, as explained [here](https://circleci.com/docs/2.0/env-vars/#overview) ("the Environment Variables page of the Build > Project > Settings in the CircleCI application").  This should be the PyPI password of the opencraft …
> Version 3.1.3, automatic PyPI uploads

- README.md
Follow up to #199 to update the docs accordingly.
> Update README to reflect PyPI usage

- circle.yml
- problem_builder/mixins.py
- problem_builder/tests/integration/test_instructor_tool.py
This PR fixes the issues causing the CI checks to fail.
* Run apt-get update before installing packages (cherry-picked from the master branch).
* Fix code style issues.
* Add a delay in the failing test for the result block content to show up.
> Fix failing CI checks

- problem_builder/tests/integration/test_instructor_tool.py
This fixes an integration test failure. The change is based on the fix in https://github.com/open-craft/problem-builder/pull/211
> Add a delay in the test for the result block content to show up

- problem_builder/tasks.py
- setup.py
When the submission of a user is not found, calling `next()` on the generator expression throws a `StopIteration` exception which was not handled. This PR adds a `try-except` handler for the exception. The `except` block does nothing because this situation is handled in the following `if` condition.
**Testing instructions**
1. Clone and Install problem_builder with the PR branch.
1. From studio Add problem builder block containing MCQ/MRQ and Instructor tool block.
1. Go to Apros and attempt question in problem builder block.
1. Do the previous step for a few users.
1. Delete one of the users used in the previous step.
1. Go to Instructor tool block in apros and click search and it will start exporting for all blocks.
1. Verify that there was no exception thrown and `(<student ID>, 'N/A', …
> [BB-643] Fix the StopIteration exception error

- problem_builder/questionnaire.py
- setup.py
This PR fixes a small bug where the button "Message Review(s)" didn't show up when using MCQ/MRQ in step builder mode.
**JIRA tickets**: [BB-807](https://tasks.opencraft.com/browse/BB-807) and MCKIN-9274
1. Install master branch on your devstack.
2. Go to Studio, in the edX Demonstration Course, and click on Settings -> Advanced Settings, then add 
`"problem-builder","step-builder" ` to `Advanced Module List` Field and click Save Changes.
2.  Create a new Section, Subsection and Unit.
3. Add the step builder component, add a mentoring step, enter in the mentoring step and add a `Multiple Response Question` and a `Multiple Choice Question`.
4. Enter on each question and check that the only options are "Add Custom Choice" and "Add Tip"
5. Checkout this branch and …
> [MCKIN-9274] Fix step-builder bug ("Message Review(s)" button not showing)

- problem_builder/models.py
- problem_builder/tests/unit/test_models.py
- requirements-dev.txt
- setup.py
This PR adds a Django signal handler to delete `Answer` objects when a `django.contrib.auth.User` object is deleted from LMS.
The `Answer` model has a field for `student_id` which stores a string [taken](https://github.com/open-craft/problem-builder/blob/john2x/BB-785-delete-xblock-custom-model/problem_builder/answer.py#L67) from `student.AnonymousUserId.anonymous_user_id`.
The signal receiver function connects to `AnonymousUserId` instead of `User` because the former will get deleted via CASCADE when the latter is deleted.
Create a test course with at least a "Long Answer Question" component from this package
The expanded setup is similar to the minimal setup, but would include modules/components from the XBlocks listed in [the Jira …
> BB-785 deleting Answer data via Django signals

- README.md
- requirements-dev.txt
This branch updates the section of `README.md` explaining how to set up the XBlock for development with the XBlock SDK.
Check out this branch and ensure the instructions produce a working workbench with the Problem Builder scenarios installed and functional, notably Mentoring Default, Mentoring Demo, and Mentoring With Only One Step.
> Update README.md with working instructions to get an XBlock development environment

- problem_builder/public/js/mentoring_with_steps.js
- setup.py
After the final attempt of assessment when the user navigates from the score summary to the feedback tips then there is discrimination between the user selected options (checkboxes) because the previously selected options are also shown in the next steps.
Please see the attached screenshots for better understanding.
**1st:**
**2nd**
**3rd**
**4th**
**5th**
CC: @msaqib52
> MCKIN-8902: Fix issue on the score summary page.

- problem_builder/public/css/questionnaire.css
This fixes a text overlap when using the feedback message functionality of the XBlock.
1. Install the `master` branch of this repo on your devstack using `pip install -e /edx/src/problem-builder` (assuming problem builder is there.
2. Create a new course, add `problem-builder` to the advanced modules and add it to a unit.
3. Add 3 multiple choice questions and fill the **Message** fields with a long text.
4. Go into the LMS and answer the questions, you should see something like this:
5. Check out this branch and test again. The issues should be fixed.
**Reviewers:**
**Authors notes:**
- Tested this on Chrome, Firefox and using multiple resolutions from 800x600 to 1920x1080. 
- Looks broken on mobile, but already looked broken before the fix and it's not in the …
> BB-1330: Fix overlapping feedback fields

- problem_builder/templates/html/mcqblock.html
- problem_builder/templates/html/mrqblock.html
- setup.py
The radio buttons and checkboxes for the mcq and mrq are not programmatically associated with its on-screen label and may not be rendered via all assistive technologies correctly. This PR links labels with their respective input fields using for attribute.
@xitij2000 could you review this PR?
> MCKIN-12122: add FOR attribute in mcq and mrq input labels

- problem_builder/public/css/questionnaire.css
- problem_builder/templates/html/mrqblock.html
- setup.py
MCKIN-12203 AF#91-MRQ-Ensure custom controls are keyboard accessible
Description
[Issue]
The feedback icons aren't keyboard accessible since div elements do not natively receive keyboard focus.
[User Impact]
When custom elements do not provide keyboard access, keyboard only users and users of assistive technology may not be able to use or interact with the custom control. 
[Code Reference]
<div class="choice-result fa icon-2x checkmark-incorrect icon-exclamation fa-exclamation" id="result_e3e109293d1944ce80c1-1" aria-label="Incorrect" data-label_correct="Correct" data-label_incorrect="Incorrect"></div>
Environment
[Recommended Solution]
Use the <button> element to ensure keyboard focus by default.
> MCKIN-12203 AF#91-MRQ-Ensure custom controls are keyboard accessible

- problem_builder/public/js/mentoring_standard_view.js
- problem_builder/templates/html/mentoring.html
- setup.py
MCKIN-12152 AF#40-MRQ-Inform assistive technologies of changes in content
[Issue]
When the submit button is activated, there is new content added to the page without notifying the user through an announcement.  Feedback text appears after the submit button.
[Resolution]
Upon activating the "Submit" button, additional content gets added beneath this button that provides feedback on the response submitted. Upon activating this button, please ensure to set focus to this newly added textual content using the JavaScript focus method, so that assistive technologies such as screen readers would be aware of this content update and would render this content to the screen reader users. Also, place a tabindex of -1 on this dynamically added feedback content container, so that it doesn't appear in …
> MCKIN-12152 AF#40-MRQ-Inform assistive technologies of changes in content

- problem_builder/public/js/mentoring_with_steps.js
- setup.py
MCKIN-12576 Stopped videos while moving to the next step
If there is more than one step in assessment and we play a video, the video keeps playing in the background when we move to the next step.
> MCKIN-12576 Stopped videos while moving to next step

- circle.yml
- setup.py
- test_requirements.in
Quick PR to see if pinning `coverage` will fix the CI issues that arose in https://github.com/open-craft/problem-builder/pull/258#issuecomment-573208358
> Pin coverage to v4

- problem_builder/mentoring.py
- setup.py
Jira ticket: https://edx-wiki.atlassian.net/browse/MCKIN-12690
Python 3:
Decimal(0.485) = 0.4849999
Decimal(48.5) = 48.5
Due to above mentioned, rounding is in-accurate.
We need to multiply score by 100 before giving it as input to Decimal(xxx).
> MCKIN-12690 Fix Score rounding

- problem_builder/answer.py
Added empty check on 'min_characters'
**Sandbox**
N/A
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
> Fixed comparison mismatch

- problem_builder/tests/integration/base_test.py
- problem_builder/tests/integration/test_completion.py
- problem_builder/tests/integration/test_step_builder.py
The tests don't appear to be flaky on my machine with python 3 any more, but this at least removes the hacky manual sleeps where possible. Instead it relies on webdriver waiting for changes to happen (element to exist, become visible, etc.). This will be faster and more reliable.
**Test instructions**:
- sanity check the code to make sure the test semantics haven't been changed
- verify that tests in CI reliably pass
**Reviewer**:
> SE-1917 Replace hacky sleeps with webdriver waits

- problem_builder/tests/integration/base_test.py
- problem_builder/tests/integration/test_completion.py
This PR fixes the CI checks which started failing after merging the `problem-builder-v4` branch to the `master` branch.
Test instructions:
* verify that tests in CI reliably pass
Reviewer:
Issue: [BB-2320](https://tasks.opencraft.com/browse/BB-2320)
> [BB-2320] Fix the CI checks after merge

- README.md
- requirements-dev.txt
Issue: [BB-2320](https://tasks.opencraft.com/browse/BB-2320)
Testing Instructions:
* Try running problem builder as given in the README, check everything is running fine.
Reviewers:
> [BB-2320] Added the MySQL Readme for Problem builder

- problem_builder/answer.py
- setup.py
Answer block is not loading js translations due to which following string is not getting translated, This PR includes js translations in answer block response.
> MCKIN-19254: fix js translations for answer block

- problem_builder/mentoring.py
- setup.py
Jira ticket https://edx-wiki.atlassian.net/browse/MCKIN-22514
There is an endpoint that was missed in #267 which needs to be addressed.
> MCKIN-22514 round off correctly for v3

- problem_builder/mentoring.py
- setup.py
Jira ticket https://edx-wiki.atlassian.net/browse/MCKIN-22514
this PR keeps up to date master for #297 
> There is an endpoint that was missed in #267 which needs to be addressed.
> MCKIN-22514 rounding off correctly

- setup.py
Since the translation is not included in the package data the following error is raised` FileNotFoundError: [Errno 2] No such file or directory: '/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/problem_builder/translations/config.yaml'`, so this forces to  install  the package from github in editable mode.
This pr includes the translation in the package data an remove locale
> Add translations to the package data

- problem_builder/models.py
Removes this warning on newer edX versions (Koa and forward):
```
2020-11-24 20:33:43,166 WARNING 4695 [py.warnings] [user None] [ip None] warnings.py:109 - /edx/src/problem-builder/problem_builder/models.py:29: DeprecatedEdxPlatformImportWarning: Importing student instead of common.djangoapps.student is deprecated
from student.models import AnonymousUserId
```
Backwards compatible with Juniper and Ironwood.
> Fix deprecated import path

- problem_builder/mentoring.py
- problem_builder/step.py
- problem_builder/tests/unit/utils.py
- setup.py
Fix imports of Video and Ooyala blocks for Juniper: 
-  `VideoDescriptor` has been replaced with [VideoBlock](https://github.com/edx/edx-platform/blob/open-release/juniper.master/common/lib/xmodule/xmodule/video_module/video_module.py#L113) 
- Imports have been [removed](https://github.com/edx-solutions/xblock-ooyala/pull/120/files) from __init__ file
> MCKIN-28611 - Nested blocks imports fix

- problem_builder/models.py
- setup.py
`common.djangoapps.student.models` must be imported differently depending on whether we're installed into a pre-Koa or post-Koa edx-platform. Koa itself can handle both import forms but raises a warning on the shortened form. See [this forum thread on import changes](https://discuss.openedx.org/t/koa-will-change-how-edx-platform-code-is-imported/3610) for more details).
Problem-builder currently decides which import path to use by looking at `settings.INSTALLED_APPS`. That works most of the time, but breaks in certain special contexts like Celery workers, which don't have the same list of installed apps. On edx.org staging yesterday we saw:
```
File "/edx/app/edxapp/venvs/edxapp/bin/celery", line 8, in <module>
sys.exit(main())
File …
```
> Import from common.djangoapps.student.models more reliably

- problem_builder/mentoring.py
- problem_builder/mixins.py
- problem_builder/models.py
- problem_builder/platform_dependencies.py
- problem_builder/swipe.py
- problem_builder/v1/upgrade.py
- setup.py
Commit:
```
For Lilac and beyond, make sure the following:
* courseware
* static_replace
* xblock_django
are instead imported as:
* lms.djangoapps.courseware
* common.djangoapps.static_replace
* common.djangoapps.xblock_django
refactor: centralize logic of edx-platform imports
in new module platform_dependencies.py.
Bump version to 4.1.11
```
Check out https://github.com/open-craft/problem-builder/pull/323 for context on the underlying import issue and our approach for handling it across different Open edX releases.
This PR just takes the strategy from #323 and applies it to three other instances of deprecated edx-platform imports. It centralizes the logic in a new file `platform_dependencies.py` as to avoid duplicating the nested `try-except` block across the project.
Related to the …
> fix: deprecated edx-platform import references

- problem_builder/tasks.py
- setup.py
Jira ticket: https://mckinsey.atlassian.net/browse/MEI-6680
Fixed `KeyError: 'student_id'` as it raises when we search username through instructor tool.
> MCKIN-12600 key error on filtering username

- problem_builder/mentoring.py
- problem_builder/platform_dependencies.py
- setup.py
Jira ticket: https://mckinsey.atlassian.net/browse/MEI-7001
Context
======
Participant should be able to submit/go through the assessment if a course author makes some changes(like deleting or reauthoring any question) in assessment through the studio.
Issue
====
Problem builder xblock does not load or gets stuck and raises value error after a question being deleted by the course author. This issue impacts only those users who had already submitted that question. Error trace from the logs as shown below:
In order to reproduce this issue, delete a question from the studio and make few changes in question choices as well.
Before publishing the changes, start attempting the assessment and then start attempting the assessment again (to complete it) after publishing the changes. By this, a …
> MEI-7001 add exception handling in case question deleted

- problem_builder/tasks.py
- setup.py
While testing celery upgrade PR in the edx-platform (https://github.com/edx/edx-platform/pull/29046/), found out that this xblock isn't compatible with celery 5.x. So this PR is making this xblock celery 5.x compatible. This xblock is private requirement of edx-platform
> feat: add support for celery 5.x

- setup.py
This fixes the `long_description` added in https://github.com/open-craft/problem-builder/pull/335.
> build: fix description content type
